### ISSUE TITLE
Logging the current lexical environment

### ISSUE THREAD

**Issue by RickMoynihan** [ptaoussanis/timbre#103]
Perhaps verging on debugging, but I think adding a macro like this to timbre would be super useful... Kinda like spy:

https://gist.github.com/RickMoynihan/9e64dafe5e9715c2766d

**Comment by ptaoussanis** [comment]
That's an awesome idea Rick, thank you - done! :-)

**Comment by RickMoynihan** [comment]
Thanks for merging, and nice idea on factoring out `get-env`
