### ISSUE TITLE
logging in v4

### ISSUE THREAD

**Issue by yogthos** [ptaoussanis/timbre#105]
I can't seem to get anything to log using version 4, this is what I've got:

```clojure
(ns timbre-test.core
  (:require [taoensso.timbre :as timbre]
                [taoensso.timbre.appenders.3rd-party.rotor :as rotor]))

(defn -main []
  (timbre/set-config!
    {:min-level :debug
     :enabled? true
     :output-fn timbre/default-output-fn})

  (timbre/merge-config!
    {:appenders
     {:rotor (rotor/rotor-appender  {:path "test.log"})}})

  (timbre/info "HELLO!!!!"))
```

I imagine I'm missing something obvious here, but based on the docs this looks like it should work. I've tried both with `:rotor` and without and I'm not seeing a log file being created nor any output in the system out.

**Comment by yogthos** [comment]
It looks like it might be a problem with the rotor appender, I tried `4.0.1` with a rolling appender and that works as expected.

**Comment by ptaoussanis** [comment]
Hi Dmitri, sorry for the delayed reply. It's very likely a bug in the rotor appender; I didn't look too closely at (or test) any of the 3rd-party appenders when migrating stuff to v4.

Just taking a couple days off from GitHub atm; will make this a priority when I'm back at work.

Sorry for the trouble!

**Comment by yogthos** [comment]
No worries, if I get a chance I'll take a look and let you know what I find. :)

**Comment by yogthos** [comment]
so turns out it was just the default log level being set to :warn that was screwing it up

**Comment by ptaoussanis** [comment]
Closing with https://github.com/ptaoussanis/timbre/commit/338b9527554f10bc77ddeabd084e26021ec8840a
