### ISSUE TITLE
Custom output format for stdout appender

### ISSUE THREAD

**Issue by narkisr** [ptaoussanis/timbre#108]
Setting a custom format should be simple but I seem to miss something 

```clojure
(defn formatting [{:keys [level throwable message timestamp hostname ns]} & [{:keys [nofonts?] }]]
     (format "%s %s" timestamp (or message "")))

(taoensso.timbre/set-config! [:fmt-output-fn] formatting)
```

Still the output does not match (it uses the default one).

It does state that appenders aren't obligated to use the for mated output but id expect the built in stdout one to be in sync.

Thanks

**Comment by ptaoussanis** [comment]
Hi Ronen, what version of Timbre are you on and what appender are you using exactly?

That looks okay for v3.4.0 and the `:standard-out` appender. Have you made any other modifications to the appender?

**Comment by narkisr** [comment]
Hey petter it was a mistake on my side, all works fine on 4.0.1, 

BTW iv imlemented a [gelf appender](https://github.com/narkisr/gelfino-client/blob/master/src/gelfino/timbre.clj) quite a while a go, take a look if you interested adding it to the README

Thanks

**Comment by ptaoussanis** [comment]
No problem, happy to hear it's working :-) Cheers!
