### ISSUE TITLE
Log to File and Stdout?

### ISSUE THREAD

**Issue by creese** [ptaoussanis/timbre#111]
I'm creating an event store. I need certain lines to log to a file. I also need regular application logs. I don't want app logs in the store or vice versa. Is this possible with timbre or should I be looking at a different lib? Can you provide a sketch of the config?

**Comment by ptaoussanis** [comment]
Hi Charles,

There are a few ways of doing this with Timbre depending on your preferences. Please see the documentation for more info.

Feel free to reopen if there's something specific in the documentation that you could use clarification on.
