### ISSUE TITLE
Log to STDOUT and sometimes to a File?

### ISSUE THREAD

**Issue by creese** [ptaoussanis/timbre#113]
I need to log to STDOUT and sometimes only to a file. I'm using clojure/tools.logging now. My question was, how can you configure timbre to do something like this?

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">

  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{ISO8601, UTC} [%thread] %-5level %logger{18} - %m%n</pattern>
    </encoder>
  </appender>

  <appender name="EVENT" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <!-- Support multiple-JVM writing to the same log file -->
    <prudent>true</prudent>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <fileNamePattern>event.%d{yyyy-MM-dd, UTC}.log</fileNamePattern>
    </rollingPolicy>
    <encoder>
      <pattern>%msg%n</pattern>
    </encoder>
  </appender>

  <logger name="event" additivity="false">
    <level value="info" />
    <appender-ref ref="EVENT" />
  </logger>

  <root>
    <level value="info" />
    <appender-ref ref="STDOUT" />
  </root>
</configuration>
```

When logging to STDOUT, the output should not go to the file, and vice versa.

**Comment by ptaoussanis** [comment]
> I need to log to STDOUT and sometimes only to a file.

You've got a variety of options depending on the condition/s you'd like for "sometimes":
* You can set different per-appender `:min-level`s (e.g. info+ goes to a file, trace+ goes to stdout)
* You can define separate Timbre config maps and use the appropriate config when making specific logging calls (e.g. one config map with the stdout appender only, one with the file appender only, one with both)
* You can add middleware to discard (noop) against arguments with certain arbitrary properties, namespaces, levels, etc.
* You can write/modify your appender fns to discard (noop) against arguments with certain arbitrary properties, namespaces, levels, etc.

First step: you'll need to clearly define what behaviour you want.
Second step will be to check out the [Timbre docs](https://github.com/ptaoussanis/timbre#configuration) to see which options might most easily get you the behaviour you want.
