### ISSUE TITLE
Context should be a separate map

### ISSUE THREAD

**Issue by mikesperber** [ptaoussanis/timbre#116]
I see this in the code:

```
                     ;; :context *context* ; Extra destructure's a nuisance
```

But imagine I'm writing an appender that wants to forward  the context without knowing what keys are in it.

(I'm currently trying to write a proper logstash appender.)

That's a nuisance because I need to dissoc all the Timbre native keys - the set of which I'm assuming may change in the future.

So I'd like to encourage commenting that line back in.

**Comment by ptaoussanis** [comment]
Hi Mike,

That's a sensible use-case I hand't considered; thanks for pointing it out - am in full agreement.

Will update in a min.

**Comment by ptaoussanis** [comment]
Just pushed `[com.taoensso/timbre "4.1.0-alpha2"]` to Clojars with this change. Cheers! :-)

**Comment by mikesperber** [comment]
Thanks - much appreciated! (As are the other changes 3.x -> 4.x. Much better now!)
