### ISSUE TITLE
How do I suppress ANSI colors in stacktrace in rotor-appender?

### ISSUE THREAD

**Issue by crocket** [ptaoussanis/timbre#117]
ANSI color codes make it very difficult to read stacktrace in log files.

What should I do?

**Comment by crocket** [comment]
It turned out that I had to pull out a trick to silence ANSI colors.

```clojure
(defn- turn-off-ansi-colors-in
  [appender-id log-config]
  (update-in log-config [:appenders appender-id :fn]
             (fn [f]
               (fn [data]
                 (binding [aviso-ex/*fonts* {}]
                   (f data))))))

(timbre/merge-config! (turn-off-ansi-colors-in :appender-id))
```

aviso-ex/*fonts* is an implementation detail that I don't have to know.

**Comment by crocket** [comment]
Why was it closed?

**Comment by brunchboy** [comment]
For what it’s worth another way to do this seems to be to set `:stacktrace-fonts` to `{}` in the `opts` map before calling `timbre/stacktrace`, for example modifying the default output function so it ends like this:

```clojure
(when-not no-stacktrace?
  (when-let [err (force ?err_)]
    (str "\n" (timbre/stacktrace err (assoc opts :stacktrace-fonts {})))))
```
