### ISSUE TITLE
Document how to use :stacktrace-fonts

### ISSUE THREAD

**Issue by crocket** [ptaoussanis/timbre#119]
`:stacktrace-fonts` is not documented on README or API docs.
Users who use file appenders should not have to spend hours of time to figure out how to turn off colors in appenders.

**Comment by kenrestivo** [comment]
@cocket have you considered documenting what you figured out and submitting a patch, or even just adding it here to save us all hours of pain?

Relevant: https://xkcd.com/979/

**Comment by ptaoussanis** [comment]
Hi Ken,

You can disable stacktrace fonts by overriding the `:output-fn` in your Timbre config - for example:
```clojure
(merge your-timbre-config {:output-fn (partial timbre/default-output-fn {:stacktrace-fonts {}})})
```

You can also override the output-fn on a per appender basis if you prefer. All formatting stuff's handled by the `output-fn`, so you'll often want to check `default-output-fn` as a starting point if you'd like to mod something to do with formatting.

Would be happy to see a PR to document this btw :-)

> or even just adding it here to save us all hours of pain

Could we please try cut down on this kind of hyperbole? It's unhelpful and can make folks reluctant to assist.

**Comment by kenrestivo** [comment]
Thanks! Works great.

Sorry for being so cranky.

**Comment by ptaoussanis** [comment]
No problem, thanks for the PR - will merge shortly
