### ISSUE TITLE
Add core.typed annotations

### ISSUE THREAD

**Issue by hiteshjasani** [ptaoussanis/timbre#120]
Just started using your project along with core.typed.  Now that clojure.core is mostly type annotated, consider adding type annotations to timbre.

I'll leave this note as possible help for others.  As a workaround I added the following temporary annotations to my project to address the errors from core.typed.  The annotations are overly broad, but they appease the type checker enough that I can focus back on my project.

```
(ann ^:no-check taoensso.timbre/set-level! [t/Keyword -> nil])                                                          
(ann ^:no-check taoensso.timbre/*config* t/Any)                                                                         
(ann ^:no-check taoensso.timbre/log1-fn [t/Any t/Any t/Any t/Any t/Any t/Any t/Any t/Any -> nil])
```

**Comment by ptaoussanis** [comment]
Hi there,

Would be happy to see a PR that doesn't introduce any extra dependencies! Cheers :-)
