### ISSUE TITLE
should have [taoensso.timbre.appenders.core :as appenders] on getting started? 

### ISSUE THREAD

**Issue by joefromct** [ptaoussanis/timbre#121]
Getting started might be a bit confusing for newcomers trying to write to file with the  buit in appender... i just had to look into the namespaces a bit and search for other code to determine whare appenders/spit-appender comes from and how to require it. 
 
So correct me if i'm wrong but this:
```
    (timbre/merge-config!
     {:appenders {:spit 
        (appenders/spit-appender {:fname "/val/log/some-log.log"})}})
```
doesn't work unless we have something like this:  (correct?)
```
(ns my-clj-ns  ; Clj ns => use `:refer`
  (:require
    [taoensso.timbre :as timbre
      :refer (log  trace  debug  info  warn  error  fatal  report
              logf tracef debugf infof warnf errorf fatalf reportf
              spy get-env log-env)]
    [taoensso.timbre.profiling :as profiling
      :refer (pspy pspy* profile defnp p p*)]
   [taoensso.timbre.appenders.core 
                :as appenders]  ))
```

**Comment by joefromct** [comment]
Never mind, upon a second reading i noticed this comment:

;; (:require [taoensso.timbre.appenders.core :as appenders]) ; Add to ns

**Comment by ptaoussanis** [comment]
No problem, thanks for checking! Cheers :-)
