### ISSUE TITLE
View source links in the API docs appear to be broken

### ISSUE THREAD

**Issue by cddr** [ptaoussanis/timbre#122]
For example, "view source" on the [default-output-fn](http://ptaoussanis.github.io/timbre/taoensso.timbre.html#var-default-output-fn) points to https://github.com/ptaoussanis/encore/blob/master/src/taoensso/timbre.cljx#L44 but I think it should point to https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre.cljx#L44 (i.e. s/encore/timbre).

**Comment by ptaoussanis** [comment]
Hi Andy, thanks for the report - should be working now! Cheers :-)
