### ISSUE TITLE
fix rotor credits

### ISSUE THREAD

**Issue by postspectacular** [ptaoussanis/timbre#125]
I just noticed that for some reason the author of the rotor appender is stated as Yutaka Matsubara, however this code is clearly only a slight modification of my rotor helper lib for timbre released in 2012:

https://bitbucket.org/postspectacular/rotor/src/3753978b07797ab20e67da18b5e048dcad87e834/src/com/postspectacular/rotor.clj?at=default
https://groups.google.com/forum/#!searchin/clojure/rotor/clojure/lKQLV9kvqe4/5lccfqMT6ewJ

It would be great if you could correct these ns credits. Thanks!

**Comment by ptaoussanis** [comment]
Hey Karsten, thanks a lot for pinging me about this - have corrected the author credit!

The error was my own fault, had just assumed that the original submitter was the author - but never asked to confirm. Apologies!

Cheers :-)

**Comment by postspectacular** [comment]
Thanks, mister! Rock on!
