### ISSUE TITLE
Fix documentation for Postal appender

### ISSUE THREAD

**Issue by zonpantli** [ptaoussanis/timbre#126]
Documentation for Postal appender in README says

```clojure
(postal-appender/make-appender {} ...)
```

`postal-appender/make-appender` does not exist, it should be either `postal-appender/make-postal-appender`, or the whole example should be converted to use `postal-appender/postal-appender` directly.

**Comment by ptaoussanis** [comment]
Hi Miika, thanks for the report - should be fixed now! Cheers :-)
