### ISSUE TITLE
shutdown-agents shutdown hook breaks other shutdown hooks

### ISSUE THREAD

**Issue by hadronzoo** [ptaoussanis/timbre#127]
Since shutdown hooks [run concurrently](https://docs.oracle.com/javase/8/docs/technotes/guides/lang/hook-design.html), running [`(shutdown-agents)`](https://github.com/ptaoussanis/timbre/blob/3e4e81cc8acda7706780c86a5cf7b58c2a43ad50/src/taoensso/timbre.cljx#L589-L591) within a shutdown hook will break other shutdown hooks that rely on agents. For example, logging, releasing datomic connection resources, or shutting down an http-kit server within other shutdown hooks will non-deterministically throw exceptions if `shutdown-agents` has already executed.

Can this experimental shutdown hook be opt-in?

**Comment by ptaoussanis** [comment]
Hi Joshua, thanks a lot for the report (and reference)! Have cut a `4.1.1` release that removes the experimental hook.

**Comment by hadronzoo** [comment]
Excellent, thanks!
