### ISSUE TITLE
Muting 3rd party client library log messages

### ISSUE THREAD

**Issue by kkebb** [ptaoussanis/timbre#138]
Is there support for this feature currently?

**Comment by ptaoussanis** [comment]
Hi there,

Not sure what you mean by "client library" in this context, but see [here](https://github.com/ptaoussanis/timbre#configuration) for info on how to use Timbre's ns blacklist/whitelist filters.

Does that help?

**Comment by kkebb** [comment]
What I mean by client library is basically any libraries (i.e. datomic, zookeeper, kafka, solr) used in a project. How can I use the ns blacklist/whitelist filters in the config? Can you please provide me with an example of their usage using the following map?

```clojure
{:enabled?   true
   :async?     false
   :min-level  nil
   :rate-limit nil
   :output-fn  :inherit
   :fn (<some-fn>)}
```

**Comment by ptaoussanis** [comment]
Okay, gotcha. You can disable all Timbre logging output except for your own application by calling:
`(timbre/swap-config! (fn [config] (assoc config :ns-whitelist ["your-app-root-ns.*"])))`

This'll suppress the logging output from all libraries that use Timbre, for all namespaces that don't match this whitelist pattern.

The problem in your case is that none of Datomic, Zookeeper, etc. actually use Timbre - so Timbre can't control their logging output (unfortunately).

To suppress Zookeeper logging, etc. - you'll need to figure out the necessary Java logging config to do that. Sad to say that can be tricky since it depends on what loggers are being used, etc. Some things to look up that may be useful: `commons-logging.properties`, `log4j.properties`, `simplelog.properties`.

Hope that's at least a little helpful?

**Comment by kkebb** [comment]
Yes it is helpful, thank you Sir!

**Comment by kkebb** [comment]
What would be the best way to spit the logs into a file, I noticed that you have a spit-appender implementation, however, I was wondering how can I use that function if I am unable to modify the config map (for example I would like to be able to change the default min-level from nil to info)?

**Comment by ptaoussanis** [comment]
Hi there,

> However, where, in my clojure project, would I place the log4j.properties file for ZooKeeper, Solr, etc.?

Usually anywhere that's on your [resource path](https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L281) - usu. `/resources` in your project root.

> What would be the best way to spit the logs into a file, I noticed that you have a spit-appender implementation

Yes, that's probably the appender you want.

> how can I use that function if I am unable to modify the config map (for example I would like to be able to change the default min-level from nil to info)?

Sorry, not sure I follow- what do you mean by modify the config map? You can find an example of how to enable the spit appender [here](https://github.com/ptaoussanis/timbre#file-appender).

The `(appenders/spit-appender {:fname "/path/my-file.log"})` call returns an appender which is just a Clojure map with keys: `{:enabled true :async? false :min-level nil :rate-limit nil :output-fn :inherit :fn _}`.

If you want to change any of the appender's default options, you can just merge over this map, e.g.:
`(merge (appenders/spit-appender {:fname "/path/my-file.log"}) {:min-level :info})`.

So a full example:
```clojure
(def my-info-level-spit-appender (merge (appenders/spit-appender {:fname "/path/my-file.log"}) {:min-level :info}))

(timbre/merge-config! {:appenders {:spit my-info-level-spit-appender}})
```

Does that help / make sense?

**Comment by kkebb** [comment]
Yes it does, thank you Sir!

Another question, what is the difference between :level and :min-level? I have noticed that the default for :level is debug I guess..

**Comment by ptaoussanis** [comment]
Where are you seeing `:level`? In the top-level config? Please see [here](https://github.com/ptaoussanis/timbre#configuration) for docs on the top-level config.

Basically, `:level` specifies the level currently in effect (defaults to `:debug`).
`:min-level` is an appender specific option. When non nil, it means to ignore the appender unless the current logging level is at least at this minimum.

So if we have an appender A with `:min-level :warn` and the current level is `:info` then that appender will never be used (since the :info level is < :warn level). Levels in order are:
`:trace :debug :info :warn :error :fatal :report`

Does that help?

**Comment by kkebb** [comment]
Perfect, yes indeed it does, thank you for all your help and patience!

Question about the appender's function though, I am using the same function for both of my appenders (one of the appenders is STDOUT and the other is a FILE) but the one in the file doesn't behave the same way as STDOUT with respect to formatting for some reason..

**Comment by kkebb** [comment]
So it seems that the appenders defined in clojure for timbre are of no use when a logback.xml file is in place... I configured the logback.xml to include a rolling file appender and it wrote the file as I desired, however, the spit appender that I configured in clojure wasn't being impacted whatsoever with what I had included in the logback.xml.

Here is some code:
logback.xml file
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true" scanPeriod="30 seconds">

  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <layout class="ch.qos.logback.classic.PatternLayout">
      <Pattern>
        %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
      </Pattern>
    </layout>
  </appender>

  <appender name="ROLLING" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>run.txt</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <!-- rollover daily -->
      <fileNamePattern>run-%d{yyyy-MM-dd}.%i.txt</fileNamePattern>
      <timeBasedFileNamingAndTriggeringPolicy
          class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
        <!-- or whenever the file size reaches 100MB -->
        <maxFileSize>100MB</maxFileSize>
      </timeBasedFileNamingAndTriggeringPolicy>
    </rollingPolicy>
    <encoder>
      <pattern>%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>

  <logger name="org" level="warn" additivity="false">
    <appender-ref ref="STDOUT"/>
    <appender-ref ref="ROLLING" />
  </logger>

  <logger name="kafka" level="warn" additivity="false">
    <appender-ref ref="STDOUT"/>
    <appender-ref ref="ROLLING" />
  </logger>

  <root level="info">
    <appender-ref ref="STDOUT"/>
    <appender-ref ref="ROLLING" />
  </root>
</configuration>
```

spit-appender code in clojure
```
(defn only-spit-appender!
  [& {:keys [enabled? async? min-level rate-limit output-fn fname]
      :or {min-level :info
           fname (clojure.string/join "/" [(System/getProperty "user.dir")
                                           (format "public/log/default-%s.log" (.format (java.text.SimpleDateFormat. "EEE_MMM_d_HH:mm:ss_zzz_yyyy") date))])}
      :as opts}]
  (let [final-spit (try
                     (merge spit-appender (timbre/spit-appender {:fname fname}) opts {:min-level min-level})
                     (catch Exception exception
                       (str "Invalid config specification: " (.getMessage exception))))]
    (timbre/merge-config! {:appenders {:spit final-spit}})))
```

**Comment by ptaoussanis** [comment]
No problem :-)

> I am using the same function for both of my appenders 

Sorry not sure I follow; could you please rephrase?

> So it seems that the appenders defined in clojure for timbre are of no use when a logback.xml file is in place

That's correct. Timbre is entirely separate from any Java logging libs; it's defined and controlled entirely from Clojure. Your logback.xml file will have no impact on Timbre, and your Timbre config will have no impact on Logback (or any other Java logging libs).

If you're stuck with legacy Java logging libs (e.g. for Zookeeper, etc.)- then the idea usually is:
1. Configure those loggers using logback.xml, etc.
2. Use Timbre for everything else (i.e. your own application's logging)

Does that make sense?

**Comment by kkebb** [comment]
So basically to rephrase this statement:
> I am using the same function for both of my appenders
What I meant was that each appender map in timbre has a :fn key, and in my case I was using the same function definition for both appenders.
example:
```
(def slf4j-appender
  "Timbre appender fn that delegates logging to slf4j
   To enable configure timbre to use this as an appender, e.g.
   (timbre/set-config {:appenders {:slf4j slf4j-appender}})

   The error argument is passed as the throwable to slf4j
   if available. Debug levels are used unchanged except
   :fatal which is mapped to slf4j's \"error\"."
  
  {:enabled?   true
   :async?     false
   :min-level  nil
   :rate-limit nil
   :output-fn  :inherit
   :fn (fn [{:keys [level msg_ ?err_ ?ns-str] :as data}]
         (let [^Logger logger (get-logger (or ?ns-str ""))
               message @msg_
               err @?err_]
           (if err
             (case level
               :trace  (.trace logger message err)
               :debug  (.debug logger message err)
               :info   (.info  logger message err)
               :warn   (.warn  logger message err)
               :error  (.error logger message err)
               :fatal  (.error logger message err))
             (case level
               :trace  (.trace logger message)
               :debug  (.debug logger message)
               :info   (.info  logger message)
               :warn   (.warn  logger message)
               :error  (.error logger message)
               :fatal  (.error logger message)))))})
```

**Comment by ptaoussanis** [comment]
> in my case I was using the same function definition for both appenders.

Not sure why you'd have two appenders with different names that both write to slf4j with the same options - might be missing something? Please also note that there's a standard spit appender included with Timbre, I provided an example of using it earlier.

> defined for the console.

Sorry, not sure what you mean by this. If you'd like your custom appenders to follow the standard `:output-fn` pattern, then you need to use the output fn in your appender fn.

Please see [here](https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre/appenders/core.cljx#L18) for details.

**Comment by ptaoussanis** [comment]
Assuming this is resolved, please feel free to reopen if you're still having trouble.

**Comment by matanster** [comment]
I think that writing/maintaining any fairly modest clojure project remains a kafkaesque story with regards to logging, unless this concern is handled. I mean any real-world project uses some Java library that relies on SLF4J, if not many. May I suggest linking from the documentation to here, or something to similar to that effect...

**Comment by Mechrophile** [comment]
I know this is an old thread, but you can hijack the clojure.tools.logging library to make yourself a pretty simple appender that will work with all your old-school java libraries.

Here's the gist of it.  Just like clojure.tools.logging, it will look for any configured java loggers.

`(let [logger-factory (clojure.tools.logging.impl/find-factory)
      logger (clojure.tools.logging.impl/get-logger logger-factory *ns*)]
  (fn [data] (clojure.tools.logging/log* logger (:level data) (:?err data) (force (:output_ data)))))`

**Comment by matanster** [comment]
Thanks!
