### ISSUE TITLE
AOT problem with slf4j-> timbre -> encore

### ISSUE THREAD

**Issue by kenrestivo** [ptaoussanis/timbre#145]
Noting this here since it caused at least one person to abandon timbre, and caused me to abandon slf4j-timbre:

https://github.com/fzakaria/slf4j-timbre/issues/9

Details here:
http://yogthos.net/posts/2015-12-26-AOTGotchas.html

I'm not sure what the solution might be.

**Comment by ptaoussanis** [comment]
Hi Ken, thanks for this-

> I'm not sure what the solution might be.

Sorry, just to clarify: could you define what you mean by solution here? Looks like Dmitri correctly identified the cause of the problem- i.e. that slf4j's AOT requirements are breaking the usual ability to pull in custom dependencies. (Very helpful that you pointed me to this post btw!)

So looks like I just need to cut a new release with an updated dependency? Or am I missing something?

**Comment by ptaoussanis** [comment]
Ref. https://github.com/fzakaria/slf4j-timbre/issues/8

**Comment by kenrestivo** [comment]
Fixed in slf4j-timbre 0.3.0
https://github.com/fzakaria/slf4j-timbre/issues/8
