### ISSUE TITLE
cljs sources not available, only js

### ISSUE THREAD

**Issue by hipitihop** [ptaoussanis/timbre#152]
We have project where the dev build of the app works with Dirac devtools, repl & cljs sources is visible, breakpoints etc. However a cljs.test build, although the Dirac repl connects and works and all devtools & dirac inits have run, cljs source is not visible in the sources, only js. Any ideas what could cause this ?

**Comment by ptaoussanis** [comment]
Hi, could you possibly rephrase? Not sure I understand.

Also, the more info you can provide - the more likely I'll be able to assist quickly (for example, not sure what Dirac is).
