### ISSUE TITLE
Some links on the API doc pages are 404'ing

### ISSUE THREAD

**Issue by rm-hull** [ptaoussanis/timbre#153]
e.g.
* http://ptaoussanis.github.io/timbre/taoensso.timbre.profiling.html
* http://ptaoussanis.github.io/timbre/taoensso.timbre.appenders.carmine.html
* http://ptaoussanis.github.io/timbre/taoensso.timbre.appenders.postal.html

Presume the generated codox content wasnt commited / pushed to gh-pages branch properly?

**Comment by ptaoussanis** [comment]
Fixed, thanks for the report.

**Comment by rm-hull** [comment]
Hi, also just noticed that the 'view source' links are 404'ing as well.

I think that `{filepath}` is probably not what you need at https://github.com/ptaoussanis/timbre/blob/master/project.clj#L73 - looking at the codox [readme](https://github.com/weavejester/codox#source-links), it suggests `{classpath}`, but @weavejester's example seems contra to this.

**Comment by ptaoussanis** [comment]
@rm-hull, thanks for the report - have filed a question with James. Just a heads-up that I might not be able to get back to you on this for a couple days, just travelling atm.
