### ISSUE TITLE
appender for databases

### ISSUE THREAD

**Issue by yuliu-mdsol** [ptaoussanis/timbre#154]
Hi, I updated MongoDB appender for the current version of timbre. Also I have appender working for MySQL/PostgreSQLDB. Should I submit them as PR for the third party folder?

For the MySQL/PostgreSQLDB support, I use migratus to generate database table. This involves change to the project.clj file. Not sure what is the best way to introduce it.

**Comment by ptaoussanis** [comment]
Hi there,

> Should I submit them as PR for the third party folder?

Sounds good :+1:, thank you.

> I use migratus to generate database table. This involves change to the project.clj file. Not sure what is the best way to introduce it.

I'm not familiar with migratus, sorry. Perhaps you could show me what changes would be necessary?

**Comment by yuliu-mdsol** [comment]
Thanks ptaoussanis. I will make a pull request for my changes.

For database table creation/migration, I can write up the steps in a separate document or add a wiki article.

**Comment by ptaoussanis** [comment]
Thanks @yuliu-mdsol, that sounds good

> For database table creation/migration, I can write up the steps in a separate document or add a wiki article.

Depending on how long/complex the instructions are, this might be something we can add to the appender or appender ns docstring?

**Comment by yuliu-mdsol** [comment]
Here is what I wrote for the database table creation/migration:
```
Assume we have a Postgresql database with the following information:

host: dbserver
port number: 5432
schema/database: dblog
username: dbuser
password: dbpass
The corresponding database url will be:

  postgresql://dbuser:dbpass@dbserver:5432/dblog
You can test database connection as the following:

psql -h dbserver -p 5432 -U dbuser -W
To enable database logging, add the following in profiles.clj (under :dev :env)

  :logdb true
  :database-url "postgresql://dbuser:dbpass@dbserver:5432/dblog"
To create database table for logging, run the following command:

  lein migratus migrate
```

**Comment by yuliu-mdsol** [comment]
The database table creation can be left out for user to create manually as well.

```
$ cat 20160212154000-create-logs-table.up.sql
CREATE TABLE IF NOT EXISTS logs (
  log_id bigserial primary key,
  instant timestamp NOT NULL,
  level varchar(20) NOT NULL,
  namespace varchar(50) NOT NULL,
  hostname varchar(30) NOT NULL,
  username varchar(30) NOT NULL,
  content text NOT NULL,
  error text NOT NULL
);

$ cat 20160212154000-create-logs-table.down.sql
DROP TABLE IF EXISTS logs;
```

**Comment by ptaoussanis** [comment]
Hi @yuliu-mdsol, I think you can add this to your PR's namespace docstring. Thank you :-)

**Comment by yuliu-mdsol** [comment]
ok, will do.

**Comment by ptaoussanis** [comment]
Already merged, closing
