### ISSUE TITLE
Feature request: Default date time stamp use ISO8601

### ISSUE THREAD

**Issue by aboy021** [ptaoussanis/timbre#155]
ISO 8601 is the only sane date format ([obligatory xkcd link](https://xkcd.com/1179/)).
It would be great if default-output-fn used this format, or at least had an option to enable it.

**Comment by ptaoussanis** [comment]
Hi there,

> It would be great if default-output-fn used this format, or at least had an option to enable it.

You can use `:iso8601` as the format. Please see https://github.com/ptaoussanis/timbre/pull/135 if you'd like details on why this isn't the default.

**Comment by aboy021** [comment]
Thanks for getting back to me so quickly.

I'd love to be able to use ```:iso8601```, but it looks like the change mentioned in #135 hasn't made it into the current master. None of the lovely patterns you created are in the current timbre.cljx and the only mention of iso8601 is in a comment.

It's a great feature, and if it does get merged into master, it would be great to add some mention of it to the README.md.

**Comment by ptaoussanis** [comment]
> Thanks for getting back to me so quickly.

No problem

> I'd love to be able to use :iso8601, but it looks like the change mentioned in #135 hasn't made it into the current master.

Looks like #135 has been in master since [v4.2.0](https://github.com/ptaoussanis/timbre/releases) (Dec 27 2015). There's no docs on it, but it should work - is it not for you?

Note that the actual code change was in https://github.com/ptaoussanis/encore, not timbre.cljx.

> It's a great feature, and if it does get merged into master, it would be great to add some mention of it to the README.md.

Sure, PR welcome :-)

**Comment by cjohansen** [comment]
Just spent some time trying to get timbre to print timestamps the same way basically all my other tools does it, and came by this. I would enthusiastically vote for 8601 as the default, it just takes too much mental effort to work with slightly deviating patterns like the one timbre currently uses. I'll take the `:pattern :iso8601` for now, but I'd suggest a prominent mention of that feature in the readme.

**Comment by ptaoussanis** [comment]
Will update the default pattern with the next release 👍

**Comment by cjohansen** [comment]
Awesome, thanks!
