### ISSUE TITLE
"No such var" exception in 4.3.0

### ISSUE THREAD

**Issue by rationalism** [ptaoussanis/timbre#157]
Just upgraded from 4.2.1 to 4.3.0. During testing, got this exception when calling the profile macro:

"CompilerException java.lang.RuntimeException: No such var: taoensso.timbre/log1-macro"

Downgrading to 4.2.1 fixed the problem.

**Comment by ptaoussanis** [comment]
Thanks for the report, forgot to update something in the profiling macro

**Comment by ptaoussanis** [comment]
Should be fixed in v4.3.1 (on Clojars now)
