### ISSUE TITLE
How to use set-config! to output to a file

### ISSUE THREAD

**Issue by chrismurrph** [ptaoussanis/timbre#161]
A few people don't know how to log to a file. Here's my SO question: 

http://stackoverflow.com/questions/36588781/timbre-set-config-has-changed-arity-thus-dont-know-how-to-use-it-to-output-s

Here's another identical one (so mine might not last):

http://stackoverflow.com/questions/35639153/clojure-timbre-4-0-set-config

**Comment by ptaoussanis** [comment]
Hi Chris,

Usage of the spit (file) appender is documented in the README at https://github.com/ptaoussanis/timbre#file-appender

Hope that helps, cheers!

**Comment by chrismurrph** [comment]
Hi Peter,
Thanks. I'll work it out and post the answer to SO.

**Comment by ptaoussanis** [comment]
Sorry Chris, not sure I follow what needs working out? 

The README gives an example that you should be able to just copy+paste, no? Or do you specifically want to use the `set-config!`?

**Comment by chrismurrph** [comment]
True - it was copy/paste: it works. The thing is to me 'appenders' seemed
like something advanced. Hence I skipped over them in the documentation and
assumed something would need to be worked out to use them.

 ~ Chris Murphy
Seaweed Software P/L (www.strandz.org)
Mobile: +61 403 162 669
CMTS: +61 2 4229 7133
Skype Name: chrismurrph

**Comment by ptaoussanis** [comment]
> True - it was copy/paste: it works.

Great, thanks for the confirmation.

> The thing is to me 'appenders' seemed
like something advanced. Hence I skipped over them in the documentation and
assumed something would need to be worked out to use them.

Understood, no problem.

Fwiw, there's no magic going on underneath. Timbre's config's just one big map as in https://github.com/ptaoussanis/timbre#configuration. You can modify the map using Clojure's standard utils like `assoc`, `merge`, `assoc-in`, etc.

Cheers :-)

**Comment by chrismurrph** [comment]
Something I just noticed is that the messages are now going to the file and to the console, whereas in the legacy example I'm pretty sure the output was going to just the file. So next part of the question is how to turn off logging to console.

**Comment by ptaoussanis** [comment]
The stdout appender is located at `[:appenders :println]` and is enabled by default.

```clojure
(timbre/merge-config!
  {:appenders
   {:println nil ; Remove println appender
    :spit (appenders/spit-appender {:fname "/path/my-file.log"})}})
```

Will do the trick

**Comment by chrismurrph** [comment]
That doesn't work for me.

**Comment by ptaoussanis** [comment]
You might need to provide some more details than "that doesn't work".

Unfortunately going to need to sign off on this issue, have my hands a bit full atm. Would encourage you to check out the docs, otherwise someone else on here should hopefully be able to assist.

Best of luck, cheers! :-)

**Comment by chrismurrph** [comment]
Adding the mapentry `:println nil` to the config hash map has no effect for me. This means that output goes to the console as well as to the file. I expected the output to go only to the file.

**Comment by chrismurrph** [comment]
Thanks for confirming andreasthoelke.
