### ISSUE TITLE
logstash appender?

### ISSUE THREAD

**Issue by mikesperber** [ptaoussanis/timbre#162]
I maintain this:

https://github.com/active-group/timbre-logstash

Would this be a candidate for inclusion in Timbre proper? (It does drag in dependencies on `clj-time` and `cheshire`.) We use it in production, so I'd be happy to maintain it for the foreseeable future.

If there's interest, I'll clean it up and submit a pull request.

**Comment by ptaoussanis** [comment]
Hi Mike,

Sure, always happy to see appender PRs! :-) Guidelines are at https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre/appenders/example.clj if possible.

Deps aren't a problem, you'll just need to add them to the relevant dev profile - and mention them in your appender ns docstring.

**Comment by ptaoussanis** [comment]
Closing for now, feel free to submit that PR whenever you like - cheers! :-)
