### ISSUE TITLE
appenders can't be removed using (merge-config! {:appenders {:appender-name nil}})

### ISSUE THREAD

**Issue by andreasthoelke** [ptaoussanis/timbre#163]
Using [com.taoensso/timbre "4.3.1"] in a fresh project, when I run

```clojure
(-> (timbre/merge-config! {:appenders {:println nil}})
    :appenders
    :println)
```

I get:

```clojure
{:enabled? true,
 :async? false,
 :min-level nil,
 :rate-limit nil,
 :output-fn :inherit,
 :fn #object[taoensso.timbre.appenders.core$println_appender$fn__24977 0x7e0d7a88 "taoensso.timbre.appenders.core$println_appender$fn__24977@7e0d7a88"]}
```

instead of `nil`, as I would expect.

Similarly appenders that I add with `merge-config!`

```clojure
(timbre/merge-config! {:appenders {:spit (appenders/spit-appender {:fname "log.txt"})}})
```

can't be removed via `merge-config!`

```clojure
(-> (timbre/merge-config! {:appenders {:spit nil}})
    :appenders
    :spit)
```

returns:

```clojure
{:enabled? true,
 :async? false,
 :min-level nil,
 :rate-limit nil,
 :output-fn :inherit,
 :fn #object[taoensso.timbre.appenders.core$println_appender$fn__24977 0x7e0d7a88 "taoensso.timbre.appenders.core$println_appender$fn__24977@7e0d7a88"]}
```

With regards to disabling (vs. removing) an appender (which seemed to be the problem here [https://github.com/ptaoussanis/timbre/issues/161]), you can still do

```clojure
(timbre/merge-config! {:appenders {:println {:enabled? false}}})
```
I.e.

```clojure
(-> (timbre/merge-config! {:appenders {:println {:enabled? false}}})
    :appenders
    :println)
```

returns `enabled? false`:

```clojure
{:enabled? false,
 :async? false,
 :min-level nil,
 :rate-limit nil,
 :output-fn :inherit,
 :fn #object[taoensso.timbre.appenders.core$println_appender$fn__24977 0x7e0d7a88 "taoensso.timbre.appenders.core$println_appender$fn__24977@7e0d7a88"]}
```
as expected.

**Comment by ptaoussanis** [comment]
Hey Andreas, thanks so much for the detailed report. Have pushed a fix that'll go out with the next Timbre release. 

In the meantime, your suggestion to use `(timbre/merge-config! {:appenders {:println {:enabled? false}}})` is good.  Otherwise folks can just mod their Timbre config map manually using the standard Clojure API, so something like: `(swap-config! assoc-in [:appenders :println] nil)`, etc.

Cheers :-)

**Comment by andreasthoelke** [comment]
Thank you Peter! Yep, the config approach seems simple and super flexible. 

Good point in using 

```clojure
(timbre/swap-config! assoc-in [:appenders :println :enabled?] false)
```
over
```clojure
(timbre/merge-config! {:appenders {:println {:enabled? false}}})
```
as the former makes the path to the config param more readable. 
And of cause you can have a helper like
```clojure
(def set-log-config-param! (partial timbre/swap-config! assoc-in))
```
and then be even more consise and also compatible with the timbre v3.4.0 set-config! syntax:
```clojure
(set-log-config-param! [:appenders :println :enabled?] false)
```
I wonder if a similar timbre/set-config-param! would make sense to ease transitioning
log configs between v3 and v4?

**Comment by ptaoussanis** [comment]
Hi Andreas, no problem :-)

> I wonder if a similar timbre/set-config-param! would make sense to ease transitioning
log configs between v3 and v4?

Do you think this is a common problem? Is it because new users don't know how to use `assoc-in`? (Sincere question).

**Comment by andreasthoelke** [comment]
Yeah, I think `(timbre/swap-config! assoc-in [:appenders :println :enabled?] false)` will do fine. It makes it clear what is happening under the hood.
Thanks again for the considerate response!
