### ISSUE TITLE
Issue with Boot-cljs and .cljx?

### ISSUE THREAD

**Issue by arichiardi** [ptaoussanis/timbre#167]
Hello Peter,

this is not really a timbre issue but something that might need to be handled.
Specifically, it looks like `boot-cljs` does not add `.cljx` files to the classpath anymore therefore resulting in `timbre` macros not available in newer project.

I can have a look at this but it of course needs your blessing first.

Thanks!

**Comment by ptaoussanis** [comment]
Hi Andrea, thanks for the report.

.cljc unfortunately requires Clojure 1.7+ while Timbre still targets Clojure 1.5+. Would like to transition to .cljc, but haven't decided on a timeframe for that yet.

Don't use Boot myself so not familiar with what the situation is there - but would suggest that if Boot's only recently having a problem with .cljx files, then the right solution might be to first try solve the issue there?

Unfortunately won't have an opportunity to investigate this myself, so would very much welcome it if you (or anyone else) felt like digging into the Boot issue and reporting back.

Much thanks, cheers! :-)

**Comment by arichiardi** [comment]
Thanks for your answer! so basically `lein-cljsbuild` compiles fine with cljs `1.7.228` ? Can you include the `debug, warn...` macros? I gotta try that.

I was thinking about this, and while I would like to discover what is the issue, after trying yesterday briefly I came to the conclusion that in any case `.cljx` is deprecated and is never going to come back so I might as well focus on the porting of timbre...

**Comment by arichiardi** [comment]
So the issue is not ClojureScript, boot or whathaveyou, but *myself* !
Of course! I had Clojure > 1.7.0 in my deps!!

The two following deps (of course) work for timbre:
```
(def clojure-dep '[org.clojure/clojure "1.6.0" :scope "provided"])
(def clojurescript-dep '[org.clojure/clojurescript "1.8.51" :scope "provided"])
```

I am still willing to give a try to the porting, should be a straigh-forward syntax change right?

**Comment by arichiardi** [comment]
I had a look but I was stuck when I saw a couple of def-ed globals like this:
https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre.cljx#L171

**Comment by ptaoussanis** [comment]
Hi, sorry, just to clarify: this is okay to close?

**Comment by arichiardi** [comment]
Hey @ptaoussanis, yes it is ok to close if you don't want to proceed, I gave it a try but I need more guidance to complete the feat. Which is probably not going to be worth it, what do you think?

**Comment by ptaoussanis** [comment]
Hi there, not sure I follow. To clarify: proceed with what? Sorry, juggling a number of things atm - would help if you could be explicit. Last I understood from this issue was a dependency problem that you resolved, no?

Thanks! :-)

**Comment by arichiardi** [comment]
No problem at all :smile: I was thinking about the porting to `cljc`, for which I can help but I need some guidance...however this specific issue can be closed yes.

**Comment by ptaoussanis** [comment]
Ahh, gotcha - no problem :-) As I mentioned - cljc unfortunately requires Clojure 1.7+ but Timbre still officially targets Clojure 1.5+ for now. A port to cljc would mean a compatibility break w/o buying much in exchange. 

So I'm definitely interested in moving to cljc eventually, but not quite yet (perhaps around Clojure 1.9?)

Re: current situation - not sure what `boot`'s doing in your case, but in general the use of cljx can+should be considered an implementation detail; i.e. shouldn't affect your project if you're just pulling Timbre in as a dependency.

Hope that makes sense?

Cheers! :-)
