### ISSUE TITLE
Race in [3rd-party] rotor-appender

### ISSUE THREAD

**Issue by mikesperber** [ptaoussanis/timbre#168]
We're seeing truncation of log files with rotor-appender.
It seems there's an obvious race when logging is done from multiple threads:
If multiple invocations of `rotate-logs` run concurrently (actually quite probable), then one might delete the logs the other just shifted into the position of the oldest log.
I suggest setting `async?` to `true`.

**Comment by ptaoussanis** [comment]
Hi Mike, thanks for the report. 

I'm not involved with any of the 3rd-party appenders and have my hands pretty full atm but would be happy to see a PR that protects against the race condition. (E.g. a simple atom to help lock rotation).

Cheers! :-)

**Comment by ptaoussanis** [comment]
Decided to just handle this myself quickly, thanks again for the report - cheers!

**Comment by mikesperber** [comment]
Ups, sorry, didn't see this until now. Might still find the test useful.

**Comment by ptaoussanis** [comment]
No problem, appreciate the PR - thanks!
