### ISSUE TITLE
ETA on cutting a next release?

### ISSUE THREAD

**Issue by seankibler** [ptaoussanis/timbre#170]
Have any estimation on when logstash appender will be released in a version? I'm currently looking to use it in a project I'm working on but I see it is only in master branch and not in a tagged version.

In the meantime I'm working around by simply copying the source file into my project. Is there something holding the release up that I can help with?

**Comment by ptaoussanis** [comment]
Hi Sean. No reason, just a shortage of time to cut a release. Will try w/in the next week.

Cheers :-)

**Comment by seankibler** [comment]
No problem, just thought I was a little crazy when it wasn't available in the 4.3.1 release. Providing the logstash appender from within my app is working just fine.

**Comment by ptaoussanis** [comment]
Cutting a new release, ETA: 5 mins.
