### ISSUE TITLE
ns-whitelist/ns-blacklist at the appender level

### ISSUE THREAD

**Issue by zamaterian** [ptaoussanis/timbre#171]
Hi it would be very nice to configure white/black-listing for a specific appender. 
I know it possible to do with-level, but that is not preferable when using 3'rd party libs. 

example:

```clojure

:println {:enabled? true 
             :ns-whitelist  [] #_["my-app.foo-ns"]
             :ns-blacklist  [] #_["taoensso.*"]
}
````

**Comment by ptaoussanis** [comment]
Hi Thomas,

I'd be open to looking over a PR that adds this. Shouldn't be difficult; you can check for current uses of the `inherit-over` fn to see how similar behaviour is currently implemented for other appender-level overrides.

Cheers :-)

**Comment by ptaoussanis** [comment]
Just implemented myself quickly while prepping the next release, cheers :-)
