### ISSUE TITLE
Request: profiling across threads

### ISSUE THREAD

**Issue by arkdrag** [ptaoussanis/timbre#173]
Recreation script

Observe that the bits wrapped in futures are missing in the 2nd example.

```
dev> (profiling/profile :info :sleepy-threads
    (dotimes [n 5]
      (Thread/sleep 100) ; Unaccounted
      (profiling/p :1ms  (Thread/sleep 1))
      (profiling/p :2s   (Thread/sleep 2000))
      (profiling/p :50ms (Thread/sleep 50))
      (profiling/p :rand (Thread/sleep (if (> 0.5 (rand)) 10 500)))
      (profiling/p :10ms (Thread/sleep 10))
      "Result"))
16-06-29 20:16:05 INFO [dev:?] - Profiling:  :dev/sleepy-threads 
             Id      nCalls       Min        Max       MAD      Mean   Time% Time
       :dev/2s           5      2.0s       2.0s   12.68μs      2.0s      84 10.0s
     :dev/rand           5   10.14ms   500.19ms   235.2ms  206.17ms       9 1.03s
     :dev/50ms           5   50.14ms    50.16ms    6.12μs   50.15ms       2 250.77ms
     :dev/10ms           5   10.13ms    10.17ms   14.22μs   10.15ms       0 50.73ms
      :dev/1ms           5    1.12ms     1.16ms   13.39μs    1.13ms       0 5.67ms
    Clock Time                                                          100 11.84s
Accounted Time                                                           96 11.34s

nil
dev> (profiling/profile :info :sleepy-threads
    (dotimes [n 5]
      (Thread/sleep 100) ; Unaccounted
      (deref (future (profiling/p :1ms  (Thread/sleep 1))))
      (deref (future (profiling/p :2s   (Thread/sleep 2000))))
      (profiling/p :50ms (Thread/sleep 50))
      (profiling/p :rand (Thread/sleep (if (> 0.5 (rand)) 10 500)))
      (profiling/p :10ms (Thread/sleep 10))
      "Result"))
16-06-29 20:17:31 INFO [dev:?] - Profiling:  :dev/sleepy-threads 
             Id      nCalls       Min        Max       MAD      Mean   Time% Time
     :dev/rand           5   10.15ms    500.2ms   235.2ms  304.17ms      12 1.52s
     :dev/50ms           5   50.13ms    50.17ms   10.07μs   50.15ms       2 250.77ms
     :dev/10ms           5   10.14ms    10.17ms    7.25μs   10.15ms       0 50.74ms
    Clock Time                                                          100 12.33s
Accounted Time                                                           15 1.82s
```

Ideally the profiling functionality would work across thread boundaries, however I don't really see any incredibly elegant solutions there.  If nothing else, documentation should be added to let users know that it won't work across thread boundaries.

**Comment by ptaoussanis** [comment]
Hi Robert,

> If nothing else, documentation should be added to let users know that it won't work across thread boundaries.

The documentation for v4.5.0 states that profiling is thread-local, e.g. (for `profile`): "When logging is enabled, executes named body with thread-local profiling enabled and logs profiling stats. Always returns body's result."

The docstring for `pspy`: "Profile spy. When thread-local profiling is enabled, records execution time of named body. Always returns the body's result."

To clarify: is that okay, or are you suggesting a specific warning that profiling won't work across threads?

> Ideally the profiling functionality would work across thread boundaries,

It's possible (just use Clojure's dynamic bindings which have binding conveyance); but the tradeoff is significantly increased profiling overhead.

Is this a common real-world pattern in your case, or you were just experimenting?

**Comment by arkdrag** [comment]
I have no idea how common it is for most people.  I tend to do a lot of performance profiling on multi-threaded code.  I typically use yourkit for this sort of thing, but I thought this would be a good lightweight way to get an idea of how tweaks I was making were working while I was in a repl session, but it didn't work for me for this reason.  I probably wouldn't sacrifice performance overhead for functionality here personally.  Obviously up to you though.  I'd be happy to submit the PR to make that change if you did want to go down that route to support the profiling of multithreaded code.  

I think the commit you made satisfies my request for explicitly calling out the thread boundary issue in the documentation.  I don't think ThreadLocal semantics are common knowledge.  Most people writing application level code simply don't have to deal with them at all.

**Comment by ptaoussanis** [comment]
> I tend to do a lot of performance profiling on multi-threaded code

Me too, though I tend to prefer being explicit about what work is being done on each thread. I.e. if I'm creating a future then I'll usually want to decide on a case-by-case basis whether or not to enable detailed profiling for the thread, or if I just care how how long the future took to deref.

If that makes sense?

The design as of v4.5.0 assumes that you'll call `profile` in your future if you want detailed profiling there too.

> Obviously up to you though. I'd be happy to submit the PR to make that change if you did want to go down that route to support the profiling of multithreaded code.

Let me think about it a little. No need for a PR; the previous version of Timbre actually worked across thread boundaries but I recently pulled that feature since few people seemed to use it, and it often caused confusion.

**Comment by ptaoussanis** [comment]
Running a quick poll on this at https://twitter.com/ptaoussanis/status/748761787223252992

**Comment by ptaoussanis** [comment]
Closing, will have utils in v4.6.0 to get multi-threaded profiling without the previous overhead costs or lack of control.
