### ISSUE TITLE
@palletops/log-config doesn't work with current version

### ISSUE THREAD

**Issue by tangrammer** [ptaoussanis/timbre#178]
Hi guys, after trying to find a replacement for `Library to help manage Timbre logging config` as @palletops/log-config did it, I've not found anything yet

could you recommend the default way that people does for that?

thanks a lot!
Juan

**Comment by ptaoussanis** [comment]
Hi Juan, what specifically are you trying to do that you're having trouble with?

**Comment by tangrammer** [comment]
Hi @ptaoussanis,
sorry not providing fully description before,
I thought was obvious ...
trying to apply different levels depending namespace
so for example
level/info => my.domain.database
level/debug => my.domain/webservices

I did it with my last project using timbre and palletops/log-config so i was lost with the broken update 

thanks in advance!

**Comment by tangrammer** [comment]
BTW: the error i got when trying to use palletops/log-config is 
```
CompilerException java.lang.RuntimeException: Unable to resolve var: timbre/levels-compare in this context, compiling:(/Users/tangrammer/git/tangrammer/log-config/src/com/palletops/log_config/timbre.clj:14:19) 

```

**Comment by ptaoussanis** [comment]
Hi there, this should be doable with Timbre's middleware feature.

You might be able to check `palletops/log-config` to see exactly how the feature was implemented there; in all likelihood only minor modifications will be necessary.

Unfortunately have my hands very full atm so won't be able to assist more directly myself. Best of luck!

**Comment by tangrammer** [comment]
Thanks @ptaoussanis  for the directions, I'll try it :)

**Comment by ptaoussanis** [comment]
No problem. Just to provide a little guidance:

[this](https://github.com/ptaoussanis/timbre/blob/1c7b67b99ae840c985bc0e6631a765799822da54/src/taoensso/timbre.cljx#L114) is where you'll add your middleware fn to your Timbre config.

This'll be a `(fn [data-map])` that gets called for every Timbre logging request.

Depending on the contents of `data-map`, you can choose to:
1. Return (pass through) the unmodified data map,
2. Return a modified data map, or
3. Return nil to completely suppress the logging call

The `data-map` will include everything as documented [here](https://github.com/ptaoussanis/timbre/blob/1c7b67b99ae840c985bc0e6631a765799822da54/src/taoensso/timbre.cljx#L74).

In your case you'll want to look at the `:level` and `:?ns-str` keys to decide when to suppress logging calls (return nil).

For example, your middleware could have a map of namespace strings to minimum logging levels, etc.

Hope that helps, cheers!

**Comment by tangrammer** [comment]
Hi @ptaoussanis !
finally i could manage/write some code to have the expected behaviour 
I'd like to clean it a bit so maybe i could contribute too

thanks a lot for your great work

**Comment by ptaoussanis** [comment]
No problem, happy it worked out! Cheers :-)
