### ISSUE TITLE
Occasional 'UnknownHost' logs; Unreliable get-hostname.

### ISSUE THREAD

**Issue by dfrese** [ptaoussanis/timbre#179]
Hello,

in a long running production environment, we observed that the hostname of log messages is occasionally 'UnknownHost'. The cause is of course not timbre's fault, but I can think of three possible remedies (for us):

1. When the lookup in get-hostname fails, use the previous cached result instead of 'UnknownHost'
2. Add some (new?) timbre configuration setting, to set a fixed hostname
3. Write a middleware to replace :_hostname for all messages (if that's possible).

Which one would you prefer? (We can create pull requests if desired)

David.

**Comment by ptaoussanis** [comment]
Hi there, I'd suggest using a simple middleware to replace all `:_hostname` values using whatever strategy you'd like re: unknown hosts.

Have also [broken up](https://github.com/ptaoussanis/timbre/commit/e971196ecf8ec0537609e6e537d94e9d0f8fc07f) the current hostname stuff into smaller parts for your convenience.

Cheers!

**Comment by dfrese** [comment]
Thanks!
