### ISSUE TITLE
TIMBRE_LEVEL environment var doesn't seem to work

### ISSUE THREAD

**Issue by brabster** [ptaoussanis/timbre#182]
Hi there,

Not sure if I'm just doing something wrong, but I'm trying to set the log level using the TIMBRE_LEVEL environment variable without effect:

```bash
$ TIMBRE_LEVEL='warn' lein repl
Compile-time (elision) Timbre level: :warn
```
```clojure
=> (require '[taoensso.timbre :as log])
=> (log/info "foo")
16-07-18 14:38:23 localhost.localdomain INFO [my.namespace:1] - foo
nil
=> (deref #'taoensso.timbre/compile-time-level)
:warn
```

Am I not using this feature correctly?

Thanks

**Comment by ptaoussanis** [comment]
Hi Paul,

Can't spot anything obviously wrong with what you've written there. 

What version of Timbre are you using? 

With Timbre v4.6.0:
```
(alter-var-root #'timbre/compile-time-level (constantly :warn))
(macroexpand '(timbre/info "foo")) ; => nil
```

Do you get different results if you run that on your side?

**Comment by brabster** [comment]
Hmmm, it's working now - and my 'warn' literal string is throwing. I wonder if my shell had gotten messed up somehow. I'll raise it again if I can add any context...
