### ISSUE TITLE
How to pretty print with Timbre

### ISSUE THREAD

**Issue by pate** [ptaoussanis/timbre#184]
Can I get Timbre to always pretty-print Clojure data structures, without modifying all my logging calls to Timbre?

**Comment by ptaoussanis** [comment]
Hi Petrus, should be doable; would recommend looking into Timbre's middleware support.

Cheers!

**Comment by theronic** [comment]
I never managed to get this going. Anyone have a middleware sample with pretty-printing Timbre?

**Comment by MrOerni** [comment]
@theronic 
I use:
```clojure
(fn [data] 
  (update data :vargs (partial mapv #(if (string? %) 
                                         % 
                                         (with-out-str (pprint %))))))]
```

The `if string? `is there, because `pprint` would print a strings with `\"`.


You could use `condp` for some advanced formating
```clojure
(fn [x] 
 (condp #(%1 %2) x
  string? (clojure.string/upper-case x)
  neg? (str "minus " (* -1 x))
  (with-out-str (pprint x))
```

**Comment by urzds** [comment]
Maybe include this example in the readme?
