### ISSUE TITLE
view source in API docs doesn't work.

### ISSUE THREAD

**Issue by jstrength** [ptaoussanis/timbre#186]
Specifically I clicked on view source for log-and-rethrow-errors function. It happens for other ones too. The link takes me to a 404 page on github.

**Comment by ptaoussanis** [comment]
Hi, last I checked this was an issue with Codox- Ref. https://github.com/weavejester/codox/issues/118

**Comment by jstrength** [comment]
Ok, I see, I didn't know that those links were auto generated by that tool. I guess this can be closed? Or kept open until they've fixed their bug and it has propagated to these API.
Thanks for the quick responds.
