### ISSUE TITLE
Support timestamp-opts support in ClojureScript

### ISSUE THREAD

**Issue by danielcompton** [ptaoussanis/timbre#190]
It would be handy if we could use the `:timestamp-opts` key in ClojureScript to add short timestamps to our js logging. Currently we override the default-output-fn but this feels a little gross. I'm not sure if you'd want to add an optional dependency on cljs-time to do the heavy lifting here?

Is there a reason that it's not implemented for CLJS other than no need and difficulty?

cc: @hipitihop

**Comment by ptaoussanis** [comment]
Hi Daniel,

Modding the default output fn is appropriate and shouldn't feel gross, that's what it's there for :-)

> Is there a reason that it's not implemented for CLJS other than no need and difficulty?

Combination no simple way of doing it, and less value in trying (I'm not sure how much demand there'd be for client-side timestamps?). May I ask what your use case is for wanting client-side timestamps?

Not very keen to pull in any extra deps, even optionally. Would prefer folks familiarise themselves with the output-fn and feel free to mod that.

Cheers!

**Comment by danielcompton** [comment]
> May I ask what your use case is for wanting client-side timestamps?

It's just helpful to see relative timing of our logs in the console. However your prodding made me think "surely this is in Chrome already?" and sure enough it is: http://stackoverflow.com/a/24260317. There's probably little need for this at this point.

**Comment by ptaoussanis** [comment]
> However your prodding made me think "surely this is in Chrome already?" and sure enough it is

Oh nice, thanks for following up! Cheers :-)
