### ISSUE TITLE
Testing log outputs with Midje

### ISSUE THREAD

**Issue by stephanebruckert** [ptaoussanis/timbre#197]
I am using Midje to write my tests.

When using `[clojure.tools.logging :as log]` I was doing the following to check wether I got the right output (more specifically to check wether :

    (fact "Logs an error if DynamoDB returns an error"
       (my-func my-data) => irrelevant
       (provided
          (log/log* anything :error nil  "Unable to write to DynamoDB") => irrelevant :times 1))

Now that I am using Timbre, I don't know how to test what's outputted and didn't find anyone doing it.

Can you help? Can the `spy` function be of help here? Thanks

Also asked here http://stackoverflow.com/questions/39964425/testing-timbre-log-outputs-with-midje

**Comment by ptaoussanis** [comment]
Hi Stéphane,

Am afraid I'm not familiar off-hand with Midje or what facilities it might provide for these kinds of tests. Testing libs often provide a way of capturing content sent to stdout, etc.

On Timbre's end, it'd also be possible to use a custom appender that sends output somewhere that are handy for your tests to analyse. You could setup these appenders as part of your test setup, and/or use something like `timbre/with-config` for the appropriate test calls.

Hope that helps, cheers! :-)

**Comment by stephanebruckert** [comment]
Yep! `timbre/vargs->margs` is the function to monitor! 
Answer given here http://stackoverflow.com/questions/39964425/testing-timbre-log-outputs-with-midje
Thanks @ptaoussanis

**Comment by ptaoussanis** [comment]
Hi Stéphane,

Please note that this function is private, and an implementation detail. It's behaviour can change at any time without notice, would strongly recommend not depending on it in any way.

Setting up a test appender as I described above would be idiomatic, quite straight forward, and reliable now and in the future.

Cheers :-)

**Comment by stephanebruckert** [comment]
You are right!

*core.clj*

    (defn init
      ([level]
        (init level {}))
      ([level config]
        (timbre/merge-config! config)
        (timbre/set-level! level)
        (timbre/info "will be printed")
        (timbre/debug "won't be printed")))

----------

*core_test.clj*

    (:require [timbre-midje.core :as core]
                   [midje.sweet :refer :all]))

    (defn log-stub [level message])
    
    (def log-stub-appender
      {:appenders
        {:test-appender
          {:enabled? true
           :fn (fn [data] (log-stub (:level data) (:vargs data)))}}})
    
    (fact "print info but not debug"
      (core/init :info log-stub-appender) => nil
      (provided
        (log-stub :info ["will be printed"]) => irrelevant :times 1
        (log-stub :debug ["won't be printed"]) => irrelevant :times 0))

**Comment by ptaoussanis** [comment]
Hey Stéphane, that's looking promising.

Depending on what you're actually hoping to test, another option in the same direction might be something like this:

```clojure
  (defmacro captured-logging-data
    [config & body]
    `(let [output# (atom nil)]

       (timbre/with-config
         (assoc ~config
           :appenders ; Overwrite appenders
           {:capture
            {:enabled? true
             :fn (fn [data#] (swap! output# #(conj (or % []) data#)))}})
         ~@body)

       @output#))

(comment
  (captured-logging-data {:level :info}
    (timbre/info  "foo")
    (timbre/debug "bar")))
```

This'll take an arbitrary config, but replace any appenders with a single appender that captures all appender data to a vector.

This way you can check any aspects of the appender data that you'd like, bringing back that capability from your earlier approach with `timbre/vargs->margs`.

In this case for example, you might want to check something like:

```clojure
(count
  (captured-logging-data {:level :info}
    (my-func my-data))) ; => 1, as expected
```

Hope that helps, cheers! :-)
