### ISSUE TITLE
Bump version of encore

### ISSUE THREAD

**Issue by AlexanderMann** [ptaoussanis/timbre#201]
## Motivation
Started playing around with Tufte (great by the way!) and got the following:

```
CompilerException clojure.lang.ExceptionInfo: Insufficient `com.taoensso/encore` version. You may have a Leiningen dependency conflict (see http://goo.gl/qBbLvC for solution). {:min-version "2.85.0", :your-version "2.79.1"}, compiling:(taoensso/tufte.cljc:45:1) 
```

Fix was simple:

```
                 [com.taoensso/timbre "4.7.4"
                  :exclusions [com.taoensso/encore]]
                 [com.taoensso/tufte "1.1.0"]
```

Seems kind of silly to have to do this and would be great to just have everything working out of the box!

**Comment by ptaoussanis** [comment]
Thanks for the report Alexander! Do always bump all dependency versions on each new release, just haven't had an opportunity (or urgent cause) to cut a new Timbre release yet :-)

Please note that you can also just rearrange your deps there, if that's more convenient:

```clojure
[com.taoensso/tufte "1.1.0"] ; Newer deps on top
[com.taoensso/timbre "4.7.4"]
```

Cheers! :-)

**Comment by AlexanderMann** [comment]
_shudder_ but then my deps would be non-alphabetically ordered! This is a scary Halloween indeed.

**Comment by ptaoussanis** [comment]
:-)

**Comment by ptaoussanis** [comment]
Will be bumping with the next release, cheers! :-)
