### ISSUE TITLE
Please to release a new version

### ISSUE THREAD

**Issue by chao787** [ptaoussanis/timbre#205]
I personally heavily rely on the timbre and some new accepted PRs.
It has been a long time developing without release.

If master branch is stable enough, do you mind to release a new timbre version?

**Comment by ptaoussanis** [comment]
Hi Richard,

Sure- will try get a new release out later in the week. Have just been in the process of relocating, so have some catching up to do on the open source :-)

Cheers!

**Comment by ptaoussanis** [comment]
So sorry for the delay, wrapping up some last commits now to cut a new release later today!
