### ISSUE TITLE
Configuring timbre log levels based on namespace

### ISSUE THREAD

**Issue by vandr0iy** [ptaoussanis/timbre#208]
Hi there!
I'm trying to replace the old `clojure.tools.logging` based configuration with timbre in the application I'm working on, and I noticed that I can configure the root log level and the namespace filter white/blacklist in 3 different ways; But with `logback.xml`-based configuration I could do this:
```xml
<logger name "my.awesome.namespace" level="TRACE" />
<root level="ERROR">
  <appender-ref="FILE" />
  ...
</root>
```
which would mean that I can actually log up to the `TRACE` level from `my.awesome.namespace`, and up to `ERROR` from other places. How do I do this in timbre?

Thank you in advance

**Comment by ptaoussanis** [comment]
Hi :-) Timbre doesn't specifically currently support different logging levels per namespace, but does support arbitrary middleware fns, etc. which'd let you get the same effect (or any other effect) with a little work.

Please check out the `timbre/example-config` docstring for some details, and feel free to ping again if you need more assistance writing the specific middleware.

Cheers! :-)

**Comment by vandr0iy** [comment]
That's a shame :( Regardless, I whipped up a middleware fn that, somehow, is able to do that. I'm posting it here, whenever anybody needed that in the future:
```clojure
(defn log-by-ns-pattern
  [ns-patterns & [{:keys [?ns-str config level] :as opts}]]
  (let [namesp   (or (some->> ns-patterns
                              keys
                              (filter #(and (string? %)
                                            ((ns-filter %) ?ns-str)))
                              not-empty
                              (apply max-key count))
                     :all)
        loglevel (get ns-patterns namesp (get config :level))]
    (when (and (log/may-log? loglevel namesp)
               (log/level>= level loglevel))
      opts)))
```
and, it must be added to the general configuration this way:
```clojure
;stuff
:middleware     [(partial mw/log-by-ns-pattern hashmap-with-ns-patterns)]
;other stuff
```
What it does precisely is: given the data structure to be logged (as the 2nd arg) determines whether the logging will actually happen or not by looking up in the configuration hashmap (1st arg), which has either the namespace string filters as specified in `taoensso.encore/ns-filter` - or the keyword `:all`- as keys, and the level as a value (es. `:debug`)

A small example of the hashmap passed as the first argument:
```clojure
{"my.beloved.ns.i.work.on.*" :debug
 "i.need.to.trace.this" :trace
 :all :error}
```
Naturally, all this stuff will work as intended for all the levels that are above the default one (the value of `:level` in the configuration), so you may want to set it to something really low, such as `:debug`.

Hoping that my explanation was clear enough and that it will be useful for someone who needs to have a similar feature in his/her logging configuration :)

**Comment by yonatane** [comment]
@vandr0iy ns-filter can't be resolved in your function.

**Comment by vandr0iy** [comment]
@yonatane sorry for not specifying that elsewhere: it's a memoized version I made earlier of `taoensso.encore/compile-ns-filter`.
```
(import '[taoensso.encore :as enc])
(defn ns-filter [fltr] (-> fltr enc/compile-ns-filter enc/memoize_))
```

**Comment by dluksza** [comment]
@ptaoussanis how about adding @yonatane ns filter middleware to timbre as a standard filter so that we don't need to copy it over?

**Comment by yonatane** [comment]
@vandr0iy your code is now in a repo I created: https://github.com/yonatane/timbre-ns-pattern-level

**Comment by ptaoussanis** [comment]
Thanks @yonatane! Will close here to focus future discussions at #210.
