### ISSUE TITLE
Generalise ns-filters to support per-filter minimum log levels?

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/timbre#210]
Ref. #208

Haven't given this much thought, but should be relatively simple to add support for mapping filters to min log levels. E.g. something like:

```clojure
{"foo.bar.*" :info 
 #{"my.app" "my.app.core"} :never} ; etc.
```

May be an interesting feature to consider? Please ping if there's interest.

Cheers :-)

**Addendum**: may also be a good time to consider backwards-compatible support for arbitrary (Tufte-like) integer levels?

**Comment by RyanFrench** [comment]
This would be great. I'm currently doing a lot of work with AWS Java libraries, which are incredibly spammy during testing, but I still want to know if the library has logged an error or warning.

For now I can write a custom appender to do it, but it would be much nicer if the ns-blacklist let me specify to only print logs above a certain threshold for a namespace.

**Comment by 64BitChris** [comment]
Yes, I agree this would be really great.  I also use the AWS Java libraries and blacklisting the http library makes one miss any errors or warnings but not blacklisting them creates a ton of log spam.

**Comment by ptaoussanis** [comment]
This'll be coming to Timbre core when I have some free time.

In the meantime, please note that @yonatana has published a [library](https://github.com/yonatane/timbre-ns-pattern-level) that I believe adds the same capability.

**Comment by RickMoynihan** [comment]
Literally just spent 10 minutes writing the same thing, and then found this!  Great that it's on the way.

**Comment by jumarko** [comment]
Is there any update on this one?

**Comment by ptaoussanis** [comment]
Feature will be in upcoming release
