### ISSUE TITLE
No appenders could be found for logger

### ISSUE THREAD

**Issue by abcdw** [ptaoussanis/timbre#212]
Hello, thanks for your library.

I faced some problem, that I can't solve yet.
I have pretty simple config: 
```clojure
(def log-config
  {:level :debug
   :ns-blacklist ["com.zaxxer.hikari.*"]})

(timbre/merge-config! log-config)
```
resulting config is:
```clojure
{:level :debug,
 :ns-whitelist [],
 :ns-blacklist ["com.zaxxer.hikari.*"],
 :middleware [],
 :timestamp-opts
 {:pattern "yy-MM-dd HH:mm:ss", :locale :jvm-default, :timezone :utc},
 :output-fn #function[taoensso.timbre/default-output-fn],
 :appenders
 {:println
  {:enabled? true,
   :async? false,
   :min-level nil,
   :rate-limit nil,
   :output-fn :inherit,
   :fn
   #function[taoensso.timbre.appenders.core/println-appender/fn--4453]}}}
```

and use https://github.com/mcohen01/amazonica library to work with amazon api.
At startup or on `lein test` it says:
```
log4j:WARN No appenders could be found for logger (com.amazonaws.AmazonWebServiceClient).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

I know, that I missed something basic, but I can't understand what.

**Comment by ptaoussanis** [comment]
Hi Andrew, so that warning (printed by log4j) actually has nothing to do with Timbre. Timbre doesn't (by default) need or use log4j or any other Java logging libs- it's all Clojure :-)

Your Clojure project is likely bringing in some dependency (AWS lib in this case) that itself uses Java logging, which is causing the warning to print.

Should be safe to ignore. To actually suppress the warning, you'll need to provide the appropriate log4j config file in your project. Not sure on the specifics off-hand, would need to Google it :-)

Hope that helps?

**Comment by abcdw** [comment]
Logging in java world is very complicated topic for me : )

Is there a way to force java logging libs use timbre appenders?

**Comment by ptaoussanis** [comment]
> Logging in java world is very complicated topic for me : )

Oh, it's very complicated for everyone. I got frustrated enough with it to write Timbre :-)

> Is there a way to force java logging libs use timbre appenders?

One option might be to take a look at https://github.com/fzakaria/slf4j-timbre but that doesn't necessarily obviate the need for still providing an appropriate log4j config.

Sorry I couldn't be of more help with suggesting a specific config- just have my hands quite full atm and as I say don't know off-hand without Googling. You can check for `log4j.properties` examples, and add this file to your project's `resources` dir.

Best of luck, cheers! :-)

**Comment by abcdw** [comment]
Thanks a lot for you help and detailed explanation.

Already saw it few months before. Will try to figure out how to work with it.

Wish you good holidays : )

**Comment by ptaoussanis** [comment]
No problem. Happy holidays, cheers! :-)
