### ISSUE TITLE
Docs unclear on how to log *only* to file

### ISSUE THREAD

**Issue by HakimCassimallyBBC** [ptaoussanis/timbre#213]
The docs suggest that to add a file appender, you should do:

```
(timbre/merge-config!
  {:appenders {:spit (appenders/spit-appender {:fname "/path/my-file.log"})}})
```

However this appears to *add* the file appender to the existing stdout one.  I couldn't find an obvious way to *replace* the existing one from reading the docs - apologies if I've missed it, but in that case, it could perhaps do with some clarification.  It looks like the following will work:

```
(timbre/set-config! (merge timbre/*config*
  {:appenders {:spit (appenders/spit-appender {:fname "/path/my-file.log"})}}))
```

But of course this is then grubbing around in the undocumented internals of timbre.  Is there a best practice I should be using instead?

**Comment by HakimCassimallyBBC** [comment]
(Sorry, made minor edits to original comment to clarify and normalise namespace naming)

**Comment by HakimCassimallyBBC** [comment]
So I got pointed at https://github.com/ptaoussanis/timbre/issues/163 and https://github.com/ptaoussanis/timbre/issues/161 which are somewhat useful.  It looks like the `swap-config!` function might be what I wanted.

(But it's not currently documented.  As removing an appender is presumably a fairly common requirement, it'd be useful to give an example usage in the docs!)

**Comment by ptaoussanis** [comment]
Hi Hakim,

Thanks for putting this out, will add a removal example in a moment! Cheers :-)

**Comment by HakimCassimallyBBC** [comment]
Thanks - that does look a bit clearer!  Though one last clarification - your example shows how to *delete* the stdout appender rather than *replace* it with a file-based appender.  Would I need to run the `merge-config!` twice, or can I do that in one go?

(I suspect I'm also confused by them both being the same type of `:spit` appender, and why then adding the file-based one didn't simply replace the stdout appender.)

**Comment by Gira-X** [comment]
I believe you are looking for this:

```clojure
(merge-config! {:appenders {:spit (spit-appender {:fname "file.log"})
                            :println {:enabled? false}}})
```

Go in a REPL and check the `*config*` var, I got the `:println` keyword from there:

```clojure
{:appenders {:println {:async? false
                       :enabled? true
                       :fn #<Fn@d106ca0 taoensso.timbre.appenders.core/println_appender[fn]>
                       :min-level nil
                       :output-fn :inherit
                       :rate-limit nil}}
 :level :debug
 :middleware []
 :ns-blacklist []
 :ns-whitelist []
 :output-fn #<Fn@567367b3 taoensso.timbre/default_output_fn>
 :timestamp-opts {:locale :jvm-default
                  :pattern "yy-MM-dd HH:mm:ss"
                  :timezone :utc}}
```

Now, it might be a tiny bit better to just remove the `:println` appender instead of disabling it.
I think you could achieve that with `set-config!`; check `timbre.cljx` for that.

**Comment by Gira-X** [comment]
For overwriting the `:println` appender entirely, you can use this:
But it has the slight disadvantage that the appender name does not fit anymore ;)

```clojure
(merge-config! {:appenders {:println (spit-appender {:fname "file.log"})}})
```

**Comment by ptaoussanis** [comment]
Thanks @Gira-X!

> Now, it might be a tiny bit better to just remove the :println appender instead of disabling it.
I think you could achieve that with set-config!; check timbre.cljx for that.

You can also just use something like:

```clojure
(merge-config! {:appenders {:spit (spit-appender {:fname "file.log"})
                            :println nil}})
```
