### ISSUE TITLE
[Cljs] Disable log on cljs

### ISSUE THREAD

**Issue by rhacker** [ptaoussanis/timbre#219]
I use this to disable log in cljs in production env but it doesn't seem to work: 
```
(timbre/merge-config! {:appenders {:console nil}})
```

**Comment by ptaoussanis** [comment]
Hi Dung-

Hmm, that should work. Can you try the following?:

```clojure
(timbre/swap-config! (fn [config] (assoc-in config [:appenders :console] nil)))
```

If that works, then I'd suggest checking that you're running the latest version of Timbre ([com.taoensso/timbre "4.8.0"]) and Encore ([[com.taoensso/encore "2.90.1"]). I seem to recall an old bug with `merge-config!` that you might be running into.

See [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md) for info on detecting potential dependency conflicts.

Cheers!

**Comment by ptaoussanis** [comment]
Assuming this is resolved, please feel free to reopen if you're still having trouble. Cheers!

**Comment by rhacker** [comment]
@ptaoussanis thanks for helping out. The problem was I have to make sure the log config ran before anything else. It was solved using component system. Thanks for helping out.

**Comment by ptaoussanis** [comment]
No problem, thanks for the update! Cheers :-)
