### ISSUE TITLE
Line-numbers would be nice

### ISSUE THREAD

**Issue by jarppe** [ptaoussanis/timbre#22]
Hello,

I tried create a pull request that would enable adding source-code line numbers to log output, but my macro-fu failed me. I just could not figure out where I should add (:line (meta &form)).

So I'm calling better programmers for the task. Would it be possible to add line number to the map that is passed to :prefix-fn function?
## 

-jarppe

**Comment by antonmos** [comment]
Considering how long CLJ-865 has been open, would it be possible to implement the workaround?
Thanks!
