### ISSUE TITLE
throw exception when uberjar

### ISSUE THREAD

**Issue by g770728y** [ptaoussanis/timbre#221]
try: 
`TIMBRE_LEVEL=':warn' lein repl`
work as expected.

but, when **uberjar**:
`TIMBRE_LEVEL=':warn' lein uberjar`
I got:
```
四月 12, 2017 10:01:53 下午 com.google.javascript.jscomp.LoggerErrorManager println
严重: /home/gouyong/dev/lightning/target/cljsbuild/public/js/out/taoensso/timbre.js:2: ERROR - Parse errorSemi-colon expected
Compile-time (elision) Timbre level: :warn
                       ^

四月 12, 2017 10:01:53 下午 com.google.javascript.jscomp.LoggerErrorManager printSummary
警告: 1 error(s), 0 warning(s)
ERROR: JSC_PARSE_ERROR. Parse error. Semi-colon expected at /home/gouyong/dev/lightning/target/cljsbuild/public/js/out/taoensso/timbre.js line 2 : 23
```

**dependencies:** 
[com.taoensso/timbre "4.8.0"]
[com.taoensso/encore "2.90.1"]

Thank's a lot ^_^

**Comment by ptaoussanis** [comment]
Hi there, thanks for the clear report!

I believe this should be fixed with `[com.taoensso/timbre "4.9.0-alpha1"]`, could you possibly try that and let me know?

If so, will cut a new stable release. Sorry for the trouble!

**Comment by g770728y** [comment]
Thanks for your quick reply!
yes, `[com.taoensso/timbre "4.9.0-alpha1"]` works :+1:  

But I get another **warning**:

`TIMBRE_LEVEL=':warn' lein uberjar`

my code:  `(spy :info (3+5)`

```四月 13, 2017 10:20:51 上午 com.google.javascript.jscomp.LoggerErrorManager println
警告: /home/gouyong/dev/lightning/target/cljsbuild/public/js/out/lightning/main/admin/template/view.js:1368: WARNING - unreachable code
}catch (e72953){if((e72953 instanceof Error)){
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

四月 13, 2017 10:20:51 上午 com.google.javascript.jscomp.LoggerErrorManager printSummary
```

**PS:** 
`(spy :error (3+5))` is ok
`debug / warn / error / fatal / report` is ok

**dependencies:**
[org.clojure.clojurescript "1.9.473"  #_"1.9.518"] 
[com.taoensso/timbre "4.9.0-alpha1"]
[com.taoensso/encore "2.90.1"]

**Comment by ptaoussanis** [comment]
> Thanks for your quick reply! yes, [com.taoensso/timbre "4.9.0-alpha1"] works 👍

Great, thanks for the confirmation! Will try cut a new stable release tomorrow.

> But I get another warning

This warning should be safe to ignore :-)

Cheers!

**Comment by ptaoussanis** [comment]
Closing, will be pushing a 4.9.0 stable in a few minutes :-)
