### ISSUE TITLE
Perhaps make deprecation notice first thing users see?

### ISSUE THREAD

**Issue by KingMob** [ptaoussanis/timbre#222]
If a user is searching, and comes to Timbre, they won't see it's been replaced by Tufte until near the end of the README. Perhaps a deprecation notice and link to Tufte should be up at the top, instead?

**Comment by ptaoussanis** [comment]
Hi Matthew,

Sorry, what makes you think Timbre has been deprecated? Only it's profiling features have been, which is why this is only mentioned in the profiling section.

Cheers :-)

**Comment by ptaoussanis** [comment]
Closing this for now but please feel free to reopen if you need to :-)

**Comment by KingMob** [comment]
My apologies! I was searching for profiling tools a couple weeks ago, and I started to use Timbre, and then I saw something about Tufte replacing it in one of the issues. I must have misunderstood.

**Comment by ptaoussanis** [comment]
No problem, thanks for clarifying :-)
