### ISSUE TITLE
What does the :report logging level mean?

### ISSUE THREAD

**Issue by weavejester** [ptaoussanis/timbre#223]
Most of the logging levels in Timbre are common to all logging systems, but there's an extra `:report` logging level in Timbre that appears to be a priority above `:fatal`. Can you possibly describe the intent of this level? It looks useful for my purposes, but I don't want to misuse it.

**Comment by ptaoussanis** [comment]
Hey James, thanks for checking.

I often find it useful to have a maximally-high logging level that doesn't also carry any specific semantic meaning (like indicating an error, etc.).

So a `report` call implies: "just log this, regardless of current logging level".
And a `:report` current logging level implies: "don't log anything but `report`s".

(I'll also often specifically configure `report` calls to send me an email, etc., but that's up to your use case). 

To be clear: none of this is special behaviour - the `:report` level works just like any of the others.

Does that help / make sense?

**Comment by weavejester** [comment]
Thanks! That makes a lot of sense, and that's pretty much exactly what I wanted to use it for. :)

**Comment by ptaoussanis** [comment]
No problem, cheers!

**Comment by Eyal-Shalev** [comment]
@ptaoussanis could you add the above to the README?
