### ISSUE TITLE
Ability to organize logs by something other than Clojure namespace...

### ISSUE THREAD

**Issue by jszakmeister** [ptaoussanis/timbre#224]
In a different application we found that having the ability to log to a different hierarchy than the source namespace is useful.  We ended up organizing the logging namespace in a way that makes more sense to administrators and made it easier to adjust settings despite any code movement.  Is there any way to specify our own namespace rather than using the current Clojure namespace?  Is this just a matter of middleware?

**Comment by ptaoussanis** [comment]
Hi John,

> We ended up organizing the logging namespace in a way that makes more sense to administrators and made it easier to adjust settings despite any code movement

Sounds good!

> Is there any way to specify our own namespace rather than using the current Clojure namespace? Is this just a matter of middleware?

Middleware seems like a good fit here. For example, you could take a first-arg keyword for all your logging calls - and your middleware could use that to set the `:?ns-str` key that gets sent to appenders, etc.

Timbre's meant to be pretty flexible- feel free to do whatever makes sense / fits your application :-)

Hope that helps?

**Comment by jszakmeister** [comment]
> Middleware seems like a good fit here. For example, you could take a first-arg keyword for all your logging calls - and your middleware could use that to set the :?ns-str key that gets sent to appenders, etc.
> 
> Timbre's meant to be pretty flexible- feel free to do whatever makes sense / fits your application :-)

Thanks Peter.  I just wanted to make sure there wasn't a better way that I was missing somehow. :-)  We'll give it a whirl and see how it works out!

**Comment by ai212983** [comment]
Just a follow-up for anyone who will run into this ticket and will decide to try: as for current version (4.10.0) black(white)listing in appenders occurs before invoking global-level middleware. Thus, changing `?ns-str` in middleware will affect only output string, but not black(white)listing.
