### ISSUE TITLE
logging eschewing the java logging levels

### ISSUE THREAD

**Issue by matanster** [ptaoussanis/timbre#227]
Not necessarily an issue, but I added the timbre dependency, required it in a namespace, and use it:

```clojure
(log "my message")
```

And I get:

> clojure.lang.ExceptionInfo: Invalid Timbre logging level

Do we need to explicitly provide configuration for getting started using the library?

**Comment by matanster** [comment]
Okay, I get it. log requires a level. 
Actually I eschew the notion of logging levels like info and warn, and try to practice aspect oriented logging. I mistakenly took `log` for being a level-agnostic logging function.

**Comment by matanster** [comment]
I would actually introduce aspect-oriented logging instead of the ambiguous traditional logging levels. By that I mean, that a logging message would optionally get tags, and a context would imply which tags will be logged and which swallowed. Or more generally, specific loggers or middleware may handle messages according to the supplied tags, through their own specific logic.

**Comment by ptaoussanis** [comment]
Hi there,

> Do we need to explicitly provide configuration for getting started using the library?

Please take a look at the [README](https://github.com/ptaoussanis/timbre/blob/master/README.md) which goes into some detail on usage, etc.

> Conceptually, this moves the game from a closed set of mutually exclusive labels, to an open set of labels enjoying disjunctive semantics.

What you're proposing isn't difficult to do with Timbre through a small middleware fn if you like. You're also welcome to effectively ignore all logging levels if you prefer by setting Timbre's active logging level to `:report`.

Hope that helps, cheers! :-)
