### ISSUE TITLE
Getting started usage of set-config!

### ISSUE THREAD

**Issue by matanster** [ptaoussanis/timbre#228]
Changing from `merge-config!` to `set-config!` and logging seems to no longer occur. I've spent some time with the source of this library, but am yet unsure how to properly set a config for the spit appender, or what the intended usage for that should be.

I am trying:

`
(set-config! {:appenders {:spit (spit-appender {:fname log-file-name})}})
`

And nothing gets logged. With `merge-config!` the same line worked like a charm.

Thanks for your advice in advance.

**Comment by matanster** [comment]
It looks like `:level :trace` is necessary to include as well, learning from other github projects using this library. I wonder where in the code does the default for `:level` sit and whether there's a very explicit default config in there; In my own fault I couldn't find one.

**Comment by ptaoussanis** [comment]
Hi there,

> I am trying: `(set-config! {:appenders {:spit (spit-appender {:fname log-file-name})}})` And nothing gets logged. With merge-config! the same line worked like a charm.

Please see the [README](https://github.com/ptaoussanis/timbre#basic-file-appender) for examples. As described there, you'll want `merge-config!` in this case.

`set-config!` entirely overwrites any pre-existing config, `merge-config!` will merge the given input with the pre-existing config.

You can check the value `timbre/*config*` to see the active config, it's just a regular Clojure map.

Hope that helps!

**Comment by matanster** [comment]
Thanks for pointing out `timbre/*config*`.

Why however would I actually want `merge-config!`, if the default config isn't a good fit for my preferences? I am not yet sure why the readme assumes that users do not oftentimes prefer to set their own values rather than merge with the defaults. Maybe reconsider the readme..
