### ISSUE TITLE
Tests and code cleanup

### ISSUE THREAD

**Issue by matanster** [ptaoussanis/timbre#229]
The source code may seem to be riddled with a lot of `comment` forms, and only has tests for 3rd party appenders. While 3rd party appenders probably run through a lot of the code base, it would be, I think, useful, to add some test code for the core of the library.

As a byproduct it may also serve as sample code for newcomers.

Otherwise I salute a library with so little tests having become so popular :smile:

**Comment by ptaoussanis** [comment]
Hi there, am fairly content with tradeoffs of the code base in its current state. Though thank you for the suggestion (offer?). Not looking for such PRs at the moment.
