### ISSUE TITLE
(log/error) crashes with make-postal-appender

### ISSUE THREAD

**Issue by Jarzka** [ptaoussanis/timbre#236]
Hi

We upgraded to the latest version of timbre (4.10.0). We noticed that Timbre crashes every time (log/error) is called and make-postal-appender is used. This worked perfectly in the previous version that we were using (3.4.0) We get the following error output:

`                harja.palvelin.main/-main       main.clj:  607
                harja.palvelin.main/-main       main.clj:  608
harja.palvelin.main/kaynnista-jarjestelma       main.clj:  592
      harja.palvelin.main/luo-jarjestelma       main.clj:  146
                    taoensso.timbre/-log!     timbre.clj:  441
                   clojure.core/reduce-kv       core.clj: 6573
              clojure.core.protocols/fn/G  protocols.clj:  174
                          clojure.core/fn       core.clj: 6547
                      clojure.core/reduce       core.clj: 6545
              clojure.core.protocols/fn/G  protocols.clj:   13
                clojure.core.protocols/fn  protocols.clj:   75
       clojure.core.protocols/iter-reduce  protocols.clj:   49
                       clojure.core/fn/fn       core.clj: 6557
                 taoensso.timbre/-log!/fn     timbre.clj:  455
                                      ...                     
              taoensso.encore/memoize-/fn     encore.clj: 1669
                       clojure.core/deref       core.clj: 2228
                                      ...                     
           taoensso.encore/memoize-/fn/fn     encore.clj: 1684
                       clojure.core/apply       core.clj:  646
                                      ...                     
                    taoensso.timbre/fn/fn     timbre.clj:  288
                  taoensso.encore/limiter     encore.clj: 2026
                 taoensso.encore/limiter*     encore.clj: 1908
    taoensso.encore/fn/coerce-limit-specs     encore.clj: 1894
                      clojure.core/reduce       core.clj: 6544
                                      ...                     
 taoensso.encore/fn/coerce-limit-specs/fn     encore.clj: 1895
                                      ...                     
java.lang.UnsupportedOperationException: nth not supported on this type: Long
`

Replacing the deprecated make-postal-appender with postal-appender fixed the issue, but it took some time to debug as the error message was not very helpful. This also raised some questions:

1) If make-postal-appender does not work anymore, why isn't it removed instead of making it deprecated? Moving to the latest version of Timbre already had many API breaking changes, so removing unworking functions would not make much harm. In fact, I think it's somewhat confusing that there are many deprecated functions inside timbre.

2) postal-appender has hardcoded min-level and rate-limit values, while the deprecated make-postal-appender allows to pass them in. Why?

**Comment by ptaoussanis** [comment]
Hi Jari,

Apologies for the trouble/confusion. It sounds like you may have been caught here by the following v3->v4 breaking API change [documented in the changelog](https://github.com/ptaoussanis/timbre/blob/master/CHANGELOG.md#v400--2015-june-10):

```
Appender :rate-limit format has changed: [ncalls ms] -> [[ncalls ms] <...>]
```

It would be helpful if you can show your entire `make-postal-appender` call to confirm, but I'm guessing that you have in there rate-limiting config from the old (v3) API?
