### ISSUE TITLE
Timestamps in CLJS

### ISSUE THREAD

**Issue by thatismatt** [ptaoussanis/timbre#239]
I'd like timestamps in my CLJS logs (I'm actually writing an Electron app, so I need my solution to work within a nodejs-like environment as well as the browser). For now I've done the workaround that is below, but I wondered if a patch for timbre adding this would be appreciated? Or if I have missed a reason that timestamps aren't included in the CLJS version.

```clojure
(defn format-date
  ([date] (format-date "yyyy-MM-dd HH:mm:ss" date))
  ([date-format date] (-> (goog.i18n.DateTimeFormat. date-format) (.format date))))

(defn with-timestamp-output-fn
  [data]
  (str (force (:timestamp_ data)) " " (log/default-output-fn nil data)))

(defn add-timestamp-middleware
  [data]
  (assoc data :timestamp_ (delay (format-date (js/Date.)))))

(log/merge-config! {:middleware [add-timestamp-middleware]
                    :output-fn with-timestamp-output-fn})
```

Thanks for the great library :)
Matt

**Comment by ptaoussanis** [comment]
Hi Matt, would be up for seeing a PR- thanks! 👍

**Comment by ptaoussanis** [comment]
Hi Matt, this looks good- thanks!

**Comment by ptaoussanis** [comment]
Merged, closing
