### ISSUE TITLE
Disable colors in color-str

### ISSUE THREAD

**Issue by devth** [ptaoussanis/timbre#240]
I use `color-str` directly in some of my logs. It's nice during dev but in prod where logs are ingested and viewed outside of a terminal I want them off. I don't think this is currently possible looking at the impl of color-str. Should it be possible via env var and/or some config? This would effectively make `color-str` a no-op when colors are disabled.

**Comment by devth** [comment]
@ptaoussanis would you be receptive to a PR that allows globally disabling colors?

**Comment by devth** [comment]
@ptaoussanis any thoughts on this?

**Comment by timgilbert** [comment]
I've wound up implementing this by passing an options map to a custom appender where it only produces color output if `(:color options)` is truthy. In my application I'm getting it out of command-line options, but it would be easy enough to use environment variables or whatnot to configure it. My code is a riff on the various solutions in #80:

```clojure
(def ^:private color-log-map
  {:info   :green
   :warn   :yellow
   :error  :red
   :fatal  :purple
   :report :blue})

(defn- color-logger [options {:keys [level output-fn] :as data}]
  (let [level-color (color-log-map level)]
    (if (and (:color options) level-color)
      (println (timbre/color-str level-color (output-fn data)))
      (println (output-fn data)))))

(defn config-timbre! [options]
  (timbre/set-config!
    {:level     :debug
     :output-fn timbre/default-output-fn
     :appenders {:color-appender
                 {:enabled? true
                  :fn       (partial color-logger options)}}})
  (timbre/set-level! (if (:debug options) :debug :info)))
```

**Comment by theronic** [comment]
How do I get Timbre to only color the log prefix, e.g. date + ERROR + namespace, but print the actual value in standard color?

While we're at it - best way to add pretty printing for Clojure data structures?

**Comment by ptaoussanis** [comment]
@devth Hi Trevor,

> Should it be possible via env var and/or some config? This would effectively make color-str a no-op when colors are disabled.

My first inclination would be to say that this sounds like it might be a better fit for something at your application layer than in Timbre core?

For example: what if someone wants to disable some but not all colour, or have separate ENV vars for controlling colour in different contexts or to different appenders, etc. This would all be fairly easy to do at the application level, but trying to keep things flexible at the Timbre level would quickly become complex.

Hope that makes sense? (Apologies for the slow+brief answer, have only a couple hours free to work through issue backlog today :-)
