### ISSUE TITLE
*context* not present in default logging

### ISSUE THREAD

**Issue by AlexanderMann** [ptaoussanis/timbre#243]
# Question
Coming from `clojure.tools.logging` I had a number of functions which utilized the NDC and MDC to make log lines more informative by default (ie, for when things were aggregated by Filebeat then viewed in Kibana etc.). In Timbre it looks like this is more or less replaced by the `*context*`, however while 3rd party appenders seem to include this by default, the `default-output-fn` (and hence the `println-appender` as well) doesn't include it.

Before running off to build a custom appender for my purposes, I'm just trying to get an idea of _why_ `*context*` isn't included by default? ie, if this causes some fun exception with streams/etc. My assumption is that this isn't the case, and that rather the `*context*` being absent by default is due to the myriad of formats that it might take/might be expected etc.

# Suggested Musical Pairing
https://www.youtube.com/watch?v=XTku4XQ0QX8

**Comment by ptaoussanis** [comment]
Hi Alexander, sorry for the delay replying.

Thanks for the clear question!

> My assumption is that this isn't the case, and that rather the *context* being absent by default is due to the myriad of formats that it might take/might be expected etc.

That's entirely correct: `*context*` is assumed to carry an application-level value/structure. A custom `output-fn` would probably most easily help here.

Cheers :-)
