### ISSUE TITLE
newrelic namespace has name that doesn't correspond with its file name

### ISSUE THREAD

**Issue by jafingerhut** [ptaoussanis/timbre#246]
The namespace name here: https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre/appenders/3rd_party/newrelic.clj#L1

is taoensso.timbre.appenders.3rd-party.appenders.newrelic

Its file name suggests that the namespace should instead be: taoensso.timbre.appenders.3rd-party.newrelic

Files containing namespaces with "mismatched" names can cause problems for tools like Leiningen, or sometimes for Clojure's require

**Comment by ptaoussanis** [comment]
Thanks Andy, this was a typo- fixed on master!
