### ISSUE TITLE
can't set log level

### ISSUE THREAD

**Issue by ftravers** [ptaoussanis/timbre#249]
i can set log level fine in clojure code, but cannot do it in clojurescript...using: 

    (log/set-level! :debug)
    (log/merge-config! {:level :debug})

but neither do anything?

I'm hoping to set the log level to :debug for use with figwheel and repl... possible?

**Comment by theronic** [comment]
Make sure your Chrome inspector logging levels include the "Verbose" option:

![image](https://user-images.githubusercontent.com/1011676/34296822-22e1656c-e71d-11e7-91f3-be9daad60d74.png)

This bit me for a long time.

**Comment by ptaoussanis** [comment]
Thanks @theronic!
