### ISSUE TITLE
Realization of LazySeqs

### ISSUE THREAD

**Issue by JoelSanchez** [ptaoussanis/timbre#253]
When I do this:
```
(taoensso.timbre/debug (for [n [1 2]] n))
```
my `output-fn` receives this as the result of `(force msg_)`:
```
"clojure.lang.LazySeq@3e2"
```
Hence I have no way to know what was there (it's now a string).
How can I solve this?

**Comment by MerelyAPseudonym** [comment]
One fix I often resort to is calling [`pr-str`](https://clojuredocs.org/clojure.core/pr-str#example-5a7a4adee4b0e2d9c35f741f) on the data before providing it to Timbre:

```clojure
(taoensso.timbre/debug "some description:" (pr-str some-data))
```

**Comment by MerelyAPseudonym** [comment]
Note: if your goal is to operate on the structured data in middleware or appenders, then `pr-str` is almost certainly _not_ the best approach. Unfortunately I don’t have any other suggestions though =/

**Comment by JoelSanchez** [comment]
My `output-fn` and appender understand Clojure data structures (the first one tries to do the parsing, while the latter tries to pprint). I'm aware I can just call `doall` before logging, but I wondered if Timbre could handle this itself.

**Comment by JoelSanchez** [comment]
```clojure
(taoensso.timbre/debug {:some :very
                        :complicated [:data :structure]
                        :that :probably
                        :spans {:a :few}
                        :lines :indeed}
                       {:this :is
                        :another [:one]})
DEBUG [user:1] - {:some :very,
                  :complicated [:data :structure],
                  :that :probably,
                  :spans {:a :few},
                  :lines :indeed}
                 {:this :is, :another [:one]}
=> nil
(taoensso.timbre/debug [:a :vector])
DEBUG [user:1] - [:a :vector]
=> nil
(taoensso.timbre/debug (for [n [1 2]] n))
DEBUG [user:1] - clojure.lang.LazySeq@3e2
=> nil
(taoensso.timbre/debug (into [] (for [n [1 2]] n)))
DEBUG [user:1] - [1 2]
```

**Comment by ptaoussanis** [comment]
@JoelSanchez Hi Joel! Please consider searching for past issues that might be helpful.

For example there's some more context at:

  - https://github.com/ptaoussanis/timbre/issues/133,
  - https://github.com/ptaoussanis/timbre/pull/200

Hope that helps, cheers :-)

**Comment by JoelSanchez** [comment]
I see this can be solved using a middleware. Nice! I'll do that.
Thanks @MerelyAPseudonym @ptaoussanis
