### ISSUE TITLE
cljs: debug messages not printed out to console

### ISSUE THREAD

**Issue by aranhoide** [ptaoussanis/timbre#256]
In timbre 4.10.0 I can't get any messages with `:debug` log level printed out to the browser console in Clojurescript (`[org.clojure/clojurescript "1.9.542"]`, Chrome, Ubuntu).

I tried setting the log level to `:trace` and I do get trace messages printed out (with a traceback, too).  `:info` log levels work fine too.  I'm not touching any other config defaults.

Neither `(debug ...)` `(debugf ...)` nor `(log :debug ...)` work, while both `(trace ...)` and `(log :trace ...)` do, so it's not some masking of the `debug` name.

I'm getting this in a private repo, but I'm happy to provide a reproduction case if this is hard at all for you to reproduce.

**Comment by aranhoide** [comment]
Nevermind; this was Chrome developer tools filtering them out.  Right after logging this I noticed a dropdown in the Chrome developer tool console where I could pick "Default" vs "All" levels.  Sorry for the noise!

**Comment by ptaoussanis** [comment]
No problem! Thanks for following up :-)
