### ISSUE TITLE
How to print JavaScript objects

### ISSUE THREAD

**Issue by derekchiang** [ptaoussanis/timbre#265]
Logging a JavaScript object using timbre results in output like this:

```
ERROR [validator.core:390] - Terminating state machine due to invalid user signature: [object Object]
```

How to correctly print a JavaScript object using timbre?

**Comment by ptaoussanis** [comment]
Hi there,

There's an undocumented feature that should help with this that I'm planning to document with the next release.
Try `(info ^:meta {:raw-console? true} js-object)`

The `^:meta {:raw-console? true}` first argument will cause the default console-appender to print arguments to the console in a raw format that should allow for browser pretty-printing.
