### ISSUE TITLE
How to make only timbre.core/spy pretty print?

### ISSUE THREAD

**Issue by ghost** [ptaoussanis/timbre#271]
I would like to make only `timbre.core/spy` pretty print, but leave all other functions alone. How do I do that?

I already found the following function in #184 for use as a middleware:
```clj
(defn pretty-log [data]
  (update
    data
    :vargs
    (partial mapv #(if (string? %)
                     %
                     (with-out-str (pprint %))))))
```

For `timbre.core/spy` this is inconvenient, however, because it will also pretty print the part before `=>`, which is usually short and just makes the logs harder to scan when pretty printed. I assume what is necessary for `timbre.core/spy` is a macro wrapping it, but I was so far unable to produce one that worked.

**Comment by ptaoussanis** [comment]
Next release of Timbre will include a `:spying?` argument in data sent to appenders, that should make customised handling easier.
