### ISSUE TITLE
Failing master build?

### ISSUE THREAD

**Issue by AndreaCrotti** [ptaoussanis/timbre#277]
I can't see any CI configuration, but when I try to run the tests myself, I just get
`Caused by: java.lang.ClassNotFoundException: android.util.Log`

So I would assume tests are just currently broken for everyone or is it just me?

**Comment by AndreaCrotti** [comment]
I tried to add a circleci config here https://github.com/ptaoussanis/timbre/pull/276

**Comment by AndreaCrotti** [comment]
So the problem is simply that in this directory
`src/taoensso/timbre/appenders/3rd_party`

there are a lot of namespaces that eventually refer to classes that are not in the given dependencies.
They are also never required by anything else so just deleting that directory makes the test pass, they should somehow be entirely ignored I guess..

**Comment by ptaoussanis** [comment]
3rd party appender deps will be in the `:test` profile on the next release, thanks for the report!
