### ISSUE TITLE
Enormous file size of :advanced CLJS build

### ISSUE THREAD

**Issue by serioga** [ptaoussanis/timbre#278]
Just FYI.

When I add/use timbre in CLJS application, the file of JS file in :advanced increases in more than 100K. This sounds like “too much” for “just a logging” library.

**Comment by michaelcameron** [comment]
The problem is with encore library upstream (https://github.com/ptaoussanis/encore/issues/37). The latest version of timbre uses 2.91.0. If you explicitly require 2.94.0 or greater, the file size goes down dramatically.

**Comment by serioga** [comment]
@michaelcameron Thank you.
