### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by xificurC** [ptaoussanis/timbre#281]
Hi, would you mind releasing a new version? A SNAPSHOT is enough too. I'm interested in using the `:ns-log-level` functionality.

**Comment by xificurC** [comment]
Is there anything I can help with to get progress on this?

**Comment by tekacs** [comment]
Following up on this @ptaoussanis -- if you would be willing to cut a release, I'm also requesting this out of interest in the ns-log-level functionality.

**Comment by ptaoussanis** [comment]
Hey everyone,
Apologies for the delay replying- will try cut a new release later today.

**Comment by ptaoussanis** [comment]
`[com.taoensso/timbre "4.11.0-alpha1"]` is now on Clojars 👍
