### ISSUE TITLE
Arity errors

### ISSUE THREAD

**Issue by borkdude** [ptaoussanis/timbre#282]
The linter [clj-kondo](https://github.com/borkdude/clj-kondo) found the following arity exceptions in this codebase:

* taoensso/timbre/appenders/3rd_party/android_logcat.clj:57:10: error: wrong number of args (1) passed to taoensso.timbre.appenders.3rd-party.android-logcat/android-logcat-appender
* taoensso/timbre/appenders/3rd_party/irclj.clj:64:10: error: wrong number of args (2) passed to taoensso.timbre.appenders.3rd-party.irclj/irclj-appender

I checked and they seem to be legit, although I haven't gone through the trouble of verifying in the REPL (in the case of Android I ran into a ClassNotFoundException).

**Comment by ptaoussanis** [comment]
Fixed, thanks!
