### ISSUE TITLE
CLJS Timbre logs default to :info, not :debug

### ISSUE THREAD

**Issue by cloojure** [ptaoussanis/timbre#284]
It seems that when using timbre for CLJS, the log level defaults to :info, not :warn as stated in the README.  

Also, it appears from my experiments that `(timbre/set-level! :debug)` must be called from the top of each file, or it has no effect on the log level.

**Comment by ptaoussanis** [comment]
Hi Alan,

The default Clj and Cljs log levels should both be [:debug](https://github.com/ptaoussanis/timbre/blob/f03cad48296836469b514bd4c74df7b17f89e070/src/taoensso/timbre.cljx#L107). Could you point out where in the README it says the default is `:warn`? That'd be wrong, I'll fix it :-)

> Also, it appears from my experiments that (timbre/set-level! :debug) must be called from the top of each file, or it has no effect on the log level.

Could you maybe provide a reproducible example? `set-level!` [mutates global state](https://github.com/ptaoussanis/timbre/blob/f03cad48296836469b514bd4c74df7b17f89e070/src/taoensso/timbre.cljx#L149), so this definitely shouldn't need to be called from each namespace individually.

Thanks!

**Comment by cloojure** [comment]
Hi - The problem has suddenly disappeared, before I could refactor out a MCV example.  I think the url may have been inadvertently pointing to an incorrect *.js output file.  I'll let you know if anything recurs.

**Comment by cloojure** [comment]
Fixed the title above (should have been :debug).  Here is an example, where no `set-level!` call is made:

```clojure
(defn init-log-level!
  "A dummy init fn to force this ns to be included in the final compiled JS"
  []
  (println "minerva._bootstrap/init! - enter")

  (log/report "-----------------------------------------------------------------------------")

  (log/report "log/report-msg"   (+ 2 3))
  (log/fatal "log/fatal-msg"   (+ 2 3))
  (log/error "log/error-msg"   (+ 2 3))
  (log/warn "log/warn-msg"   (+ 2 3))
  (log/info "log/info-msg"   (+ 2 3))
  (log/debug "log/debug-msg"   (+ 2 3))
  (log/trace "log/trace-msg"  (+ 2 3))

  (log/spy :info "log/spy-info-msg"   (+ 2 3)) ; must put level kw as first arg

  (log/report "-----------------------------------------------------------------------------")
  (println "minerva._bootstrap/init! - leave")
  )
```

which produces output in Chrome console:

```
minerva._bootstrap/init! - enter
core.js:155 REPORT [minerva._bootstrap:32] - -----------------------------------------------------------------------------
core.js:155 REPORT [minerva._bootstrap:34] - log/report-msg 5
core.js:155 FATAL [minerva._bootstrap:35] - log/fatal-msg 5
(anonymous) @ core.js:155
core.js:155 ERROR [minerva._bootstrap:36] - log/error-msg 5
(anonymous) @ core.js:155
core.js:155 WARN [minerva._bootstrap:37] - log/warn-msg 5
(anonymous) @ core.js:155
core.js:155 INFO [minerva._bootstrap:38] - log/info-msg 5
core.js:155 INFO [minerva._bootstrap:42] - log/spy-info-msg => 5
core.js:155 REPORT [minerva._bootstrap:44] - -----------------------------------------------------------------------------
core.cljs:192 minerva._bootstrap/init! - leave

```

so you see both `debug` and `trace` are skipped.  I looked at the source and saw no obvious problem, the the symptom is unmistakable.

**Comment by ptaoussanis** [comment]
Hi Alan, two ideas to check:

- Could you please print your `timbre/*config*`
- Is it possible your Chrome is configured to suppress trace/debug level console logging calls?

**Comment by cloojure** [comment]
This problem has mysteriously disappeared before I had a chance to make a MCR example.  Will let you know if I figure out something more.

**Comment by cloojure** [comment]
Big Clue!  The problem seems to manifest when I am running figwheel in with `:optimizations :none` (i.e. DEBUG level log msgs not displaying).  When I run in production with `:optimizations :advanced`, I can see the log/debug level messages.

**Comment by cloojure** [comment]
Looks like a  Chrome bug:   https://stackoverflow.com/questions/44622318/how-to-unhide-filtered-messages-in-chrome-developer-tools-on-a-mac

When I did "Reset & Restore Defaults" I could select the "verbose" mode and the `(log/debug ....)` messages were visible again.

**Comment by ptaoussanis** [comment]
Okay, thanks for updating the thread Alan! 👍
