### ISSUE TITLE
let binding vector with only one form

### ISSUE THREAD

**Issue by borkdude** [ptaoussanis/timbre#285]
let binding vector with only one form:

https://github.com/ptaoussanis/timbre/blob/f03cad48296836469b514bd4c74df7b17f89e070/src/taoensso/timbre/appenders/3rd_party/congomongo.clj#L21

Found with [clj-kondo](https://github.com/borkdude/clj-kondo)

**Comment by ptaoussanis** [comment]
Fixed, thanks!
