### ISSUE TITLE
Logstash is blocking execution when server is down

### ISSUE THREAD

**Issue by kevin-hendel** [ptaoussanis/timbre#289]
As the default value for `:async` for the logstash appender is `false` (https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre/appenders/3rd_party/logstash.clj#L60) we experienced a hard-to-debug problem when our logstash server was offline. Each log statement is stopping the execution of the program until the connection timeout is reached. 

Like in https://github.com/ptaoussanis/timbre/issues/251, setting `:async` to `true` by default may prevent this.

**Comment by ptaoussanis** [comment]
Adjusting default shortly, thanks for the report.
