### ISSUE TITLE
`spit-appender` hard-codes "\n" 

### ISSUE THREAD

**Issue by jimpil** [ptaoussanis/timbre#292]
Instead it can simply use `system-newline` from the same namespace. 

On a slightly different note, it seems that `spit-appender` actually tries to be something like a `file-line-appender`. If that's the case a slightly cheaper implementation (skips two calls to `str`) would be the following:

```clj
(with-open [^BufferedWriter wrt (io/writer fname :append append?)]
  (let [^String out (force output_)]
    (.write wrt out)
    (.newLine wrt)))
```
Furthermore, extending the above to use a shared Lock is pretty trivial too (for thread-safety mentioned in another ticket).

**Comment by ptaoussanis** [comment]
Fixing shortly
