### ISSUE TITLE
change log message format

### ISSUE THREAD

**Issue by sr3d** [ptaoussanis/timbre#297]
I'd like to see if it's possible to change the log message to make it a bit shorter for development, e.g. instead of 

`19-09-12 21:57:37 mbp INFO [my.library] - some log message`

I'd like just to log the actual message out (just the "some log message" part).

**Comment by xificurC** [comment]
This is easily configurable. Untested:

```clojure
{:level :debug
 :output-fn (fn [d] (force (:msg_ d)))
 ...
}
```
