### ISSUE TITLE
How to set a level?

### ISSUE THREAD

**Issue by yatagan** [ptaoussanis/timbre#298]
```
$ TIMBRE_LEVEL=':error' TIMBRE_NS_BLACKLIST='["io.pedestal.*" "org.eclipse.jetty.*"]' lein repl
...
Compile-time (elision) Timbre level: :error
Compile-time (elision) Timbre ns blacklist: ["io.pedestal.*" "org.eclipse.jetty.*"]
19-11-13 21:20:17 mac DEBUG [io.pedestal.http.route.definition.terse:111] - {:app-name nil, :route-count 1, :line 194}
```

So looks like Timbre understands I don't want to see debug messages and messages from `io.pedestal.*`. 
But why it shows them?

**Comment by ivarref** [comment]
Hi

I think this has to do with static initialization of slf4j-timbre and such. This issue is (probably) resolved in slf4j-timbre `"0.3.15"`, which was released after your post. Try upgrading and see if that works?

Ref https://github.com/fzakaria/slf4j-timbre/issues/32
