### ISSUE TITLE
Obfuscate credentials in logs

### ISSUE THREAD

**Issue by kumarshantanu** [ptaoussanis/timbre#3]
When a log contains credentials, esp `:password` or `"password"` as key in a map, replace the corresponding value with `"******"`. This can also be extended to patterns in text being logged.

**Comment by stephanebruckert** [comment]
@ptaoussanis I've tried setting up a middleware but it is ignored:

    16-10-19 12:42:23 MLL1P05380.local INFO [timbre-midje.core:23] - {:name "Robert Paulson", :password "Super secret"}

The code used is yours:

```
(timbre/merge-config! {
      :level :info
      :middleware
      [(fn [{:keys [hostname message] :as args}] ; Get standard appender args
          ;; Return transformed args or nil
          (cond (= hostname "filtered-host") nil ; Filter completely
                (map? message)
                (if (contains? message :password)
                  (assoc args :message (assoc message :password "*****"))
                  args)
                :else args))]})
```

Any idea?

**Comment by ptaoussanis** [comment]
Hi Stéphane,

That's a really old example up there :-) You can see [here](https://github.com/ptaoussanis/timbre#configuration) for up-to-date details on the data map supplied to appenders.

There's a `:vargs` key that you can check, so something like:

```clojure
  (defn middleware [data]
    (let [{:keys [vargs]} data
          [v1] vargs]
      (if (and (map? v1) (:password v1))
        (assoc-in data [:vargs 0]
          (assoc v1 :password "****"))
        data)))

  (middleware {:vargs [{:password "foo"}]})
```

Cheers!

**Comment by stephanebruckert** [comment]
Thanks! How would I do to not print the message at all?

**Comment by ptaoussanis** [comment]
Middleware can return nil to filter a logging call.
