### ISSUE TITLE
get-hostname caches exceptions

### ISSUE THREAD

**Issue by xificurC** [ptaoussanis/timbre#303]
I'm interrupting a thread group and occasionally the interrupt renders most of my code unusable. The reason seems to be that `get-hostname` caches the InterruptedException for 1 minute.

**Comment by ptaoussanis** [comment]
Hi @xificurC, with what version of Timbre are you seeing this? Are you able to provide a reproducible example?

Thanks!

**Comment by ptaoussanis** [comment]
Not sure precisely what's happening in your case, but have made `get-hostname` a little more robust in the next release.

**Comment by xificurC** [comment]
Hi @ptaoussanis , I'm sorry but I no longer have the code and version in a format where I could easily reproduce this. I think the sequence was

- a log call is fetching the hostname
- the thread receives an interrupt during the hostname lookup
- the interrupted exception gets cached/memoized as the result

Any other log calls would throw at that point. However if I waited 60 seconds then the logs started working.

Does that make sense? I remember thinking *a* solution would be to not cache exceptions.

**Comment by ptaoussanis** [comment]
@xificurC Thanks for the quick response!

Exceptions aren't cached, and actually the code to fetch the hostname also traps exceptions.
Two things I can imagine _may_ have been happening:

1. You were using a _really_ old version of Timbre before hostname fetching caught exceptions.
2. The code to create a thread was somehow throwing.

Have made a mod that will cover the second case. Beyond that will suggest that this can probably be closed for now, and someone can reopen if they run into trouble again with the upcoming release.

**Comment by ptaoussanis** [comment]
Closing for now as part of issue triage, please feel free to reopen if this is still relevant!
