### ISSUE TITLE
Incl. :fn-name in data sent to appenders

### ISSUE THREAD

**Issue by audriu** [ptaoussanis/timbre#304]
Something like this https://github.com/cloojure/tupelo/blob/master/src/cljc/tupelo/misc.cljc#L468

**Comment by ptaoussanis** [comment]
@audriu Hi Audrius, apologies for the long delay replying! It looks like the content of your link has changed, please always try [reference a specific commit hash](https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files) when linking to code on GitHub.

Would be open to adding additional data for appenders if you/someone can show an example of how the data could be had.

Cheers!

**Comment by audriu** [comment]
Sorry it was 3 years ago and I forgot what I meant. I probably meant adding the name of the calling function to the data as it is done in that library. I don't know if it is useful and relevant anymore...
