### ISSUE TITLE
No such var: enc/system-newline when loading timbre LATEST (4.11.0-alpha1)

### ISSUE THREAD

**Issue by camsaul** [ptaoussanis/timbre#306]
I added `[taoensso/timbre "LATEST"]` to my `:user` profile to do some testing for something and ran into this error trying to `require` `taoensso/timbre`.  

```clj
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling taoensso/timbre.clj at (58:12)
   #:clojure.error{:phase :compile-syntax-check, :line 58, :column 12, :source "taoensso/timbre.clj"}

1. Caused by java.lang.RuntimeException
   No such var: enc/system-newline
```

This are the dependencies that it ended up fetching:

```
Retrieving com/taoensso/timbre/4.11.0-alpha1/timbre-4.11.0-alpha1.pom from clojars
Retrieving com/taoensso/encore/2.120.0/encore-2.120.0.pom from clojars
Retrieving io/aviso/pretty/0.1.37/pretty-0.1.37.pom from clojars
```

**Comment by camsaul** [comment]
I'm going to use 4.10.0 for now, but thought you should know about this bug in the dev version. 

It doesn't look like this project has CI set up. I'd be happy to help with that if it's something you'd want.

**Comment by ptaoussanis** [comment]
Hi Cam, it sounds like you might have an Encore dependency conflict.
Please see [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md) for info.

Thanks
