### ISSUE TITLE
ClojureScript spit-appender

### ISSUE THREAD

**Issue by mavines** [ptaoussanis/timbre#308]
I've modified spit-appender to work in ClojureScript on Node. It adds a dependency on [cljs-node-io](https://github.com/pkpkpk/cljs-node-io) and won't work in the browser. Would it be better to add this to core.cljx or as a third-party appender (or not at all)?

**Comment by ptaoussanis** [comment]
Hi @mavines - PR welcome to add as 3rd party appender, thanks!

**Comment by josephwinston** [comment]
@mavines would it be possible to share the repo or the patch as I have a need for the spit-appender in ClojureScript?

**Comment by ptaoussanis** [comment]
Merged, thanks!
