### ISSUE TITLE
No logging output with timbre 4.10.0 and recent com.teoensso/encore versions

### ISSUE THREAD

**Issue by jsyrjala** [ptaoussanis/timbre#313]
I have a project that uses timbre 4.10.0 to log. It used to have `[com.taoensso/encore "2.122.0"]` and everything worked, logging output came to stdout. Upgrading `com.taoensso/encore` library to 2.125.0 or 2.150.1 makes the output disappear.

Effect of `com.taoensso/encore` versions:
- 2.122.0 everything works
- 2.123.0 no output
- 2.124.0 no output
- 2.125.0 fails due https://github.com/ptaoussanis/timbre/issues/312
- 2.125.1 no output

There is no output from stuff directly logged to timbre `(timbre/info "...")` and there is no output from various Java libraries that use slf4j and various slf4j bridges.

Here are logging related bits from `lein deps :tree`
```clojure
   [com.fzakaria/slf4j-timbre "0.3.19" :exclusions [[commons-logging]]]
...
   [com.taoensso/timbre "4.10.0" :exclusions [[commons-logging]]]
     [io.aviso/pretty "0.1.33"]
...
 [com.taoensso/encore "2.125.1" :exclusions [[log4j] [commons-logging]]]
   [com.taoensso/truss "1.5.0"]
   [org.clojure/tools.reader "1.3.3"]
...
   [org.clojure/tools.logging "1.1.0" :exclusions [[commons-logging]]]
...
   [org.slf4j/jcl-over-slf4j "1.7.30" :exclusions [[commons-logging]]]
   [org.slf4j/jul-to-slf4j "1.7.30" :exclusions [[commons-logging]]]
   [org.slf4j/log4j-over-slf4j "1.7.30" :exclusions [[commons-logging]]]
   [org.slf4j/slf4j-api "1.7.30" :exclusions [[commons-logging]]]
...
   [org.apache.logging.log4j/log4j-1.2-api "2.13.3" :exclusions [[log4j] [commons-logging]]]
   [org.apache.logging.log4j/log4j-api "2.13.3" :exclusions [[log4j] [commons-logging]]]
   [org.apache.logging.log4j/log4j-core "2.13.3" :exclusions [[log4j] [commons-logging]]]
```

**Comment by ptaoussanis** [comment]
Hi @jsyrjala, thanks again for the report- apologies for the trouble!

> Effect of com.taoensso/encore versions

This was very helpful, thank you!

I'm investigating now. In the meantime you might be able to help speed the investigation if you're able to share whether you're using any namespace filters (runtime or compile time?) - and what they are.

**Comment by ptaoussanis** [comment]
No need for additional info, spotted the problem.

**Comment by ptaoussanis** [comment]
Should be addressed with `[com.taoensso/encore "2.125.2"]`, now on Clojars - but will also do some additional testing later today, and hoping to cut a new release of TImbre later this weekend.

**Comment by jsyrjala** [comment]
Thanks, I tested`[com.taoensso/encore "2.125.2"]` and it works.

**Comment by ptaoussanis** [comment]
Thanks for the confirmation 👍
