### ISSUE TITLE
timbre 4.11.0-alpha1 incompatible with encore 2.124.0 (and thus nippy 2.15.1)

### ISSUE THREAD

**Issue by aiba** [ptaoussanis/timbre#314]
It may be of interest that if you have a project that includes both `[com.taoensso/timbre "4.11.0-alpha1"]` and `[com.taoensso/nippy "2.15.1"]` then timbre will not work, since this combination implies a dependency on `[com.taoensso/encore "2.124.0"]`, which seems incompatible with `[com.taoensso/timbre "4.11.0-alpha1"]`.  The behavior I'm observing with this combination is that all timbre logging just silently fails.

A fix for this is to manually include an even more recent version of encore (`[com.taoensso/encore 2.126.2"]`), which seems to work fine with timbre.

But for others who might run into this, I suggest releasing a `"4.11.0-alpha2"` with the latest encore dependency.

**Comment by ptaoussanis** [comment]
@aiba Hi Aaron, thanks for pinging about this!

Am hoping to cut a new stable release in the next week, but have quite a few changes planned for that.

In the meantime have just pushed `[com.taoensso/timbre "4.11.0-alpha2"]`. Will also bump Nippy's encore dependency shortly.
