### ISSUE TITLE
Possible deadlock in spit-appender

### ISSUE THREAD

**Issue by vincentjames501** [ptaoussanis/timbre#329]
The following commit added a new locking mechanism to the spit-appender: https://github.com/ptaoussanis/timbre/commit/d53188040188e1df214d659b8716b255c9395768

This can cause a possible deadlock if you try to log something while logging something (i.e. realizing a lazy collection).

While I realize this isn't advised, it used to work but now results in a deadlock:

```clojure
(timbre/info "root" (pmap #(timbre/info "num" %) (range 10)))
```

Note: if you fully realize the collection, there are no issues.

```clojure
(timbre/info "root" (vec (pmap #(timbre/info "num" %) (range 10))))
```

**Comment by ptaoussanis** [comment]
@vincentjames501 Thanks for the report (+ reproducible) Vincent!
