### ISSUE TITLE
5 second delays when logging

### ISSUE THREAD

**Issue by xfthhxk** [ptaoussanis/timbre#333]
Not every time but frequently we've been seeing 5 second delays in system responses and eventually traced it to logging calls.  It seems that `taoensso.timbre/get-hostname` tries to get the hostname once a minute and that call can block for at most 5 seconds. As a temporary work around we've replaced the var by doing:

```clj
(alter-var-root #'taoensso.timbre/get-hostname (constantly (fn [] "UnknownHost")))
```

**Comment by ptaoussanis** [comment]
Hi Amar! Please see https://github.com/ptaoussanis/timbre/issues/323 - hope that helps!

**Comment by xfthhxk** [comment]
Thanks Paul for the reply and the link to the other issue. We'll look into that and close this.
