### ISSUE TITLE
Elision env vars during cljs compilation creates invalid JS

### ISSUE THREAD

**Issue by jamesnvc** [ptaoussanis/timbre#335]
It seems that if I have an elision environment variable set (e.g. `TAOENSSO_TIMBRE_NS_PATTERN_END="{#{:allow #{"*"} :deny #{"some.other.core"}}`) and have clojurescript compilation running as part of the uberjar (e.g. in `project.clj` 
```
(defproject ...
;;; etc
 :profiles 
  {:uberjar
       {:prep-tasks
        ["compile"
          ["trampoline" "run" "-m" "figwheel.main" "-bo" "prod"]]}})
```

then when uberjarring, that the println from timbre.cljc ends up in the generated javascript -- the second line of timbre.js is `Compile-time (elision) Timbre ns-pattern: ...`, which causes a parse error and aborts the compilation.

**Comment by ptaoussanis** [comment]
@jamesnvc Hi James,

Thanks for the report! Any chance you could provide a minimal reproducible? Does this seem only with figwheel?

**Comment by jamesnvc** [comment]
Ah, it seems that the culprit is running figwheel with `trampoline`; if I remove the `"trampoline"` from `:prep-tasks` (which I ended up needing to do to fix other issues), then it works fine.
