### ISSUE TITLE
How to get thread and process in this way.

### ISSUE THREAD

**Issue by leon-zhang-guoao** [ptaoussanis/timbre#336]
```
(defn json-output-fn
  [{:keys [vargs_ hostname_ ?file timestamp_ level ?line ] :as args}]）
```
I can't find the parameters of 'thread' and 'process'. 
Is there any way to get them?

**Comment by ptaoussanis** [comment]
@leon-zhang-guoao Hi Leon,

These are not parameters provided by default to Timbre appenders, see [here](https://github.com/ptaoussanis/timbre/blob/7bb3d648e1a49cf835233785fe2c07e43b2395da/src/taoensso/timbre.cljc#L184).

You'll need to get any relevant thread/process info via the relevant Java API - then you could attach this info in your output fn, and/or via Timbre middleware.

Hope that helps!
