### ISSUE TITLE
How to filter namespaces more granulary

### ISSUE THREAD

**Issue by dadinn** [ptaoussanis/timbre#340]
I would like to blacklist INFO level messages from all namespaces except my project's own namespace.
Yet I would like to see WARN/ERROR level messages from every namespace.

My current config filters for my project's own namespace, and only allows INFO level or higher messages, but there is no way to do this on a namespace basis:
```
(timbre/merge-config!
      {:level :info
       :ns-blacklist  ["*"]
       :ns-whitelist  ["myproject.*"]})
```

**Comment by ptaoussanis** [comment]
Hi there! Please see the [configuration documentation](https://github.com/ptaoussanis/timbre#log-levels-and-ns-filters-basics).

**Comment by dadinn** [comment]
Sorry but the documentation is conflicting. Should I be using `:ns-filter` or `:ns-blacklist` and `:ns-whitelist`. These aren't explained. The `example-config` shows different options.
