### ISSUE TITLE
Filter by context

### ISSUE THREAD

**Issue by awb99** [ptaoussanis/timbre#347]
Is it possible to filter in an appender  by context?

**Comment by ptaoussanis** [comment]
@awb99 Sure. This can be done in the appender itself, or in middleware (if the same behaviour can/should apply to all appenders). Context [is available](https://github.com/ptaoussanis/timbre/blob/7bb3d648e1a49cf835233785fe2c07e43b2395da/src/taoensso/timbre.cljc#L206) to appenders along with other appender data.

If you want this behaviour for your own appender (fn) implementation, it's as simple as checking the value of `:context` sent to the appender in the appender fn body.

If you want this behaviour for an appender (fn) that someone else implemented (e.g. one of the built-in appenders), the easiest way would probably be to just write a little appender wrapper that checks the value of `:context` then either noops or calls the underlying appender.

Hope that helps!
