### ISSUE TITLE
How to add traceid/spanid to logs?

### ISSUE THREAD

**Issue by crinklywrappr** [ptaoussanis/timbre#348]
https://docs.datadoghq.com/tracing/connect_logs_and_traces/java/?tab=log4j2

is `with-context` the right way to do this?

**Comment by ptaoussanis** [comment]
Hi Daniel! Sorry I'm not quite sure what you're asking, could you please expand a little on what you're trying to do?

**Comment by crinklywrappr** [comment]
traceid & spanid allows datadog to correlate logs with higher-level things eg HTTP requests and database queries.

They provide instructions (in the link provided) how to add traceid and spanid to log4j/slf4j logs.

I would like to do the same with timbre but don't know how.

**Comment by crinklywrappr** [comment]
Thanks!
