### ISSUE TITLE
Docs fail to be imported into cljdoc

### ISSUE THREAD

**Issue by holyjak** [ptaoussanis/timbre#353]
CljDoc is a popular single source of docs for clojure libraries, integrated with desktop doc viewers such as Dash. Thus it would be very nice if it could also display timbre's docs. Currently https://cljdoc.org/d/com.taoensso/timbre/5.2.1 reads "import failed" [due to the error](https://app.circleci.com/pipelines/github/cljdoc/builder/35243/workflows/736e1369-4efb-4937-863d-404e2932064d/jobs/51617):

> ClassNotFoundException: android.util.Log, compiling:(taoensso/timbre/appenders/3rd_party/android_logcat.clj:38:20)

Perhaps the tips in https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#getting-dependencies-right might help? (I.e. adding the android lib as a "provided" optional dependency?)

I am sure the cljdoc people will be happy to help via Slack or an issue.

Thank you!

**Comment by ptaoussanis** [comment]
@holyjak Hi Jakub, thanks for bringing this to my attention!

It'd be great to get Timbre working with CljDoc, though it's not immediately obvious to me what'd be needed to get it working.

I don't _believe_ that `"provided"` would help here. If CljDoc tries to load all namespaces, ultimately I guess it'd either need to have those namespaces successfully load - or it'd need to be able to gracefully skip a namespace that can't be successfully loaded. To successfully load that Android appender namespace, I expect the Android the Android platform would actually need to be present.

I could be mistaken though!

I won't have the opportunity to look into this in detail right now, but would be very happy to see a PR if you or someone else can confirm a solution from Timbre's end.

If we can't think of anything to do from Timbre's end, an alternative might be to see if it'd be possible for CljDoc to skip namespaces that it can't load. Not sure what downsides that might involve, assuming it's possible.

**Comment by ptaoussanis** [comment]
Think I've found a sort of workaround for this, by moving all the community appender stuff into a different source folder that's excluded by Leiningen's default profiles.

Change will be included in a forthcoming release.

Thanks again for pinging about this 👍
