### ISSUE TITLE
Update io.aviso/pretty to 1.2

### ISSUE THREAD

**Issue by vincentjames501** [ptaoussanis/timbre#357]
There is an issue with `[io.aviso/pretty "1.1.1"]` where it can throw uncaught exceptions when trying to format an exception for certain exceptions. See https://github.com/AvisoNovate/pretty/issues/78 for more info. Should be a safe dep bump!

**Comment by ptaoussanis** [comment]
@vincentjames501 Hi Vincent, this will be updated in forthcoming release - thanks for pinging!
