### ISSUE TITLE
Community appenders no longer included in 6.0.0

### ISSUE THREAD

**Issue by captain-porcelain** [ptaoussanis/timbre#359]
After upgrading to version 6.0.0 the community appenders are no longer available in the packaged jar.
I'm aware that the namespace has changed, but that namespace is not available.
At first I thought they might be released as a separate artifact, but the readme does not say so.

**Comment by ptaoussanis** [comment]
@captain-porcelain Apologies for the trouble, this was unintentional! Thanks for pinging.

Should be fixed with [v6.0.1](https://github.com/ptaoussanis/timbre/releases/tag/v6.0.1), now on Clojars 👍

**Comment by captain-porcelain** [comment]
@ptaoussanis Thanks for the quick work to fix this. Much appreciated!
