### ISSUE TITLE
Why are my Timbre timezones different than the system ones?

### ISSUE THREAD

**Issue by WorldsEndless** [ptaoussanis/timbre#363]
When I compare the system journald logs to those output by timbre, the timbre ones are apparently in UTC where the journald is appropriately at my local timezone. Why do these mis-match and how can I get them all to be my own zone, as the system already is?

**Comment by ptaoussanis** [comment]
@WorldsEndless Hi Tory, Timbre uses UTC timestamps by default.

This is configurable via the `:timezone` option in `:timestamp-opts`.
Possible values include `:utc`, `:jvm-default`, or any other JVM `java.util.TimeZone`.

```clojure
(merge-config!
  {:timestamp-opts
   {:timezone (java.util.TimeZone/getTimeZone "Europe/Amsterdam")}}) ; etc.
```

Hope that helps!

**Comment by ptaoussanis** [comment]
Assuming this is resolved, closing.

**Comment by WorldsEndless** [comment]
This did indeed do the trick. We set to `:jvm-default` and are now getting our local time, as desired. Thank you!
