### ISSUE TITLE
shadow-cljs: Advanced build bloated since 6.0.3

### ISSUE THREAD

**Issue by DerGuteMoritz** [ptaoussanis/timbre#366]
A `shadow-cljs`-based CLJS build grew from 512K to 630K between versions 6.0.2 and 6.0.3 (and persists in 6.0.4) with advanced optimizations. I was able to further narrow down the cause to `com.taoensso/encore` by switching to  6.0.2 and overriding its encore version. Turns out that encore version 3.34.0 is the last one that produces a 512K build. Versions 0.35.0 through 0.37.x are broken (due to #364) and version 0.38.0 and later then produce the bloated 630K build.

**Comment by DerGuteMoritz** [comment]
I just tried with the following overrides to the respective latest versions:

```clojure
{com.taoensso/encore {:mvn/version "3.45.0"}
 com.taoensso/truss {:mvn/version "1.8.0"}}
```

Still produces the same result.

**Comment by ptaoussanis** [comment]
@DerGuteMoritz Hi Moritz, thanks for reporting this - and for the clear & detailed report - was very helpful!

Would you please try `[com.taoensso/encore "3.46.0-alpha1"]` and let me know if that's also producing the bloated build?

**Comment by DerGuteMoritz** [comment]
Hi Peter, thanks for the swift reply :+1:  Unfortuantely, `[com.taoensso/encore "3.46.0-alpha1"] ` doesn't make a difference (I double-checked that it's indeed being used).

**Comment by ptaoussanis** [comment]
👍 Is [com.taoensso/encore "3.46.0-alpha2"] any better?

If that's still no good, I'll try create a reproducible example on my side.

Thanks!

**Comment by ptaoussanis** [comment]
Just pushed `[com.taoensso/encore "3.46.0"]` to Clojars 👍 
Thanks so much for reporting this, apologies for the trouble!

Fix: https://github.com/ptaoussanis/encore/commit/9be0d413eeb596e11fd8541d72a00ca35aff5027
