### ISSUE TITLE
Using TAOENSSO_TIMBRE_CONFIG_EDN environment variable leads to an execption

### ISSUE THREAD

**Issue by akond** [ptaoussanis/timbre#371]
When I use 
```
export TAOENSSO_TIMBRE_CONFIG_EDN="{}"
jave -jar ...
```
I get 

> caused by: clojure.lang.ArityException: Wrong number of args (3) passed to: taoensso.encore/fn--3975/load-edn--3976

I assume `load-edn` takes 4 arguments, but it only gets called with just three: `(load-edn default edn source)`

**Comment by ptaoussanis** [comment]
@akond Hi Toropenko, thanks for the report - and apologies for the trouble!

This is indeed a bug. Please add the following dependency to your project, _before_ your Timbre dependency:

```clojure
[com.taoensso/encore "3.51.1"]
```

That should fix the problem. I'll keep this issue open for now, until I cut a new Timbre release that includes the newer Encore version with the fix.

**Comment by akond** [comment]
The workaround works for me. Thank you.

**Comment by ptaoussanis** [comment]
Great, thanks for the confirmation 👍

**Comment by ptaoussanis** [comment]
Will be addressed in a new Timbre release that I'll be pushing shortly, marking as done.
