### ISSUE TITLE
Latest release uses older com.taoensso/encore; order-dependent if used with e.g. Tufte

### ISSUE THREAD

**Issue by TuggyNE** [ptaoussanis/timbre#376]
I just upgraded Timbre and Tufte simultaneously, but unfortunately they require different versions of Encore, and Tufte specifically asserts a later version than Timbre references, so in e.g. Leiningen, the order they are declared in is suddenly significant. (The problem can also be handled by adding exclusions.) Obviously, that's a known issue that does sometimes crop up more or less unavoidably in a Maven-based build tool, but in a case where all the deps involved are from the same source, it's fairly galling.

On the plus side, the error was at least immediately clear without any faffing about with strange opaque inconsistencies for three weeks before realizing the problem. Version check good.

**Comment by ptaoussanis** [comment]
@TuggyNE Hi there!

Yes, this will inevitably (and unfortunately) happen from time to time. When there's a version mismatch, the error that's thrown is supposed to include a link to resolution instructions [here](https://github.com/ptaoussanis/encore/blob/master/DEP-CONFLICT.md) - hope that helps!

**Comment by TuggyNE** [comment]
Ah, I see the issue. I was getting the Timbre release timing (two weeks ago) confused with Sente (9 hours ago). Since Encore has had two releases in those two weeks there's not much that can be done short of just pushing out another nop Timbre release.
