### ISSUE TITLE
Clean up v2.x appenders to conform to v3.x style

### ISSUE THREAD

**Issue by ptaoussanis** [ptaoussanis/timbre#41]
The v3.0.0 Carmine and Postal appenders have adopted a new style that I'd like to see carried over into 3rd party appenders. Basically each appender ns now exposes a `make-<X>-appender` `(ƒ [& [appender-opts make-opts]])` that'll return a ready-to-use Timbre appender.

`appender-opts` are any general opts like `{:enabled? true :min-level :error}`. The appender creator fn will supply defaults, override-able with `appender-opts`.

`make-opts` are any opts specific to this appender - e.g. database connections, special formatting options, etc. The options exposed here will be up to the appender author.

If anyone feels like helping out (esp. if you're the author of a v2.x appender), please consider a PR to bring the old appenders in line with the new, more flexible style. You can see the `taoensso.timbre.appenders.postal` or `taoensso.timbre.appenders.carmine` namespaces for examples.

Thanks a ton! Feel free to ping me with questions, etc.

**Comment by devth** [comment]
Did anyone ever fix this? Was wondering why my rolling appender wasn't working :)
