### ISSUE TITLE
MDC-like contexts

### ISSUE THREAD

**Issue by prepor** [ptaoussanis/timbre#42]
Hello.

How about support of MDC-like (https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/MDC.html) log's contexts? It's especially useful with structural log-appenders (like Graylog or Logstash).

**Comment by eoliphan** [comment]
Given that it looks like some of log-config's features are now in timbre itself, would it make sense to have this in timbre now? 

Where `with-context` (or some alternative) merges the map arg with the existing parent value?

**Comment by ptaoussanis** [comment]
@eoliphan Hi Erich, `with-context` was added back in 2015: https://github.com/ptaoussanis/timbre/releases/tag/v4.0.0 :-)

**Comment by eoliphan** [comment]
Hey yeah, that's what I was referring to :).  As it stands, I guess `with-context` is more like an NDC?  The current value is the innermost context.   I was looking at more MDC like behavior where the current context is the sum/union of all parents.  For example:

```
(log/with-context
  {:outer :context}
  (log/info "outer")
  (log/with-context
    {:inner :context}
    (log/info "inner")))
; outputs
{... "context":{"outer":"context"} ...}
{... "context":{"inner":"context"} ...}
```
You'd want the map with both the :inner and :outer keys.

So basically a variant where the `binding` statement sets `*context*` to `(merge *context* ~new-context)`

**Comment by ptaoussanis** [comment]
@eoliphan Hi Erich, in that case I think you're probably looking for #262.
There's been a couple requests for that now, so I'll re-open it.

**Comment by ptaoussanis** [comment]
Addressed with https://github.com/ptaoussanis/timbre/commit/858830a08d4de80bfab37bea7449b5f363fda363
