### ISSUE TITLE
Should log to standard error out of the box?

### ISSUE THREAD

**Issue by wiseman** [ptaoussanis/timbre#49]
Do you think that timbre should log to standard error, as opposed to standard out, when used out of the box?

**Comment by ptaoussanis** [comment]
There's going to be a simple config flag for this in v4, closing.

**Comment by emlyn** [comment]
Just wondering if this config flag is available now that v4 is out?

**Comment by ptaoussanis** [comment]
Hi @emlyn, it is - see the println appender [docstring](https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre/appenders/core.cljx#L73) for details

**Comment by emlyn** [comment]
Ah yes, thanks @ptaoussanis. How do `:std-err` / `:std-out` differ from `:*err*` / `:*out*`?

**Comment by ptaoussanis** [comment]
`:std-err` is Standard Error
`:std-out` is Standard Out
`:*err*` is whatever the value is of Clojure's `*err*` dynamic var (usu. Standard Error)
`:*out*` is whatever the value is of Clojure's `*out*` dynamic var (usu. Standard Out)

Does that make sense?

**Comment by emlyn** [comment]
Oh yes, of course, I forgot that *out* and *err* might be rebound. Thanks!
