### ISSUE TITLE
Upgrade from 2.6.3 to any later kills shutdown time

### ISSUE THREAD

**Issue by vesse** [ptaoussanis/timbre#61]
Hi,

I updated a project to use the latest timbre and noticed that running `lein do drop, migrate` suddenly took 9 times more time than earlier.

I worked my way downwards and found out that this behavior starts occurring from version 2.7.0. With 2.6.x things work just fine. I did reproduce this behavior multiple times.

For some reason when a task is done and it prints its last message on screen it takes ages for the process to end (about 2 minutes). Any ideas what could be wrong?

**Comment by ptaoussanis** [comment]
Closing this, looks like there's not much that can be done from Timbre's side. Will just document the issue+workaround for now.
