### ISSUE TITLE
Feature request: syslog appender

### ISSUE THREAD

**Issue by danielsz** [ptaoussanis/timbre#73]
Hi Peter, 

I note that syslog support was never mentioned before. 

Hipsters may cling on to logging frameworks and façades like they would to skinny jeans, but there is a venerable protocol on UNIX systems called [Syslog](http://en.wikipedia.org/wiki/Syslog) that is a trusted option when deploying daemons on production servers. Call me old-fashioned.

There is an existing [implementation](https://github.com/joshrotenberg/brolog) in Clojure.  

More rationale (excerpt from [LinuxJournal](http://www.linuxjournal.com/article/4036)):

> As the number and complexity of applications on a system grows, so, too, does the complexity of the system administrator's job. Applications and their messages vary widely in their significance to certain audiences. If a number of applications are considered “critical” and their status is the system administrator's responsibility, he does not want to search to find out where and how every critical application logs its status. That's where syslogd comes in.

**Comment by nicferrier** [comment]
Any progress on this @danielsz ?

**Comment by danielsz** [comment]
@nicferrier Ah, no, never got to it, sorry. :(

**Comment by danielflower** [comment]
+1 for syslog support, unless there is another way to get Papertrail to listen to a Heroku app.

**Comment by danielflower** [comment]
I think I meant just logging to the console. I never got it to log to syslog sorry.

**Comment by ptaoussanis** [comment]
Just throwing out there that writing a Timbre appender for https://github.com/joshrotenberg/brolog looks like it should be quite straight forward + potentially a good exercise for folks wanting to get more familiar with how Timbre appenders work.

There's an example appender that you can use as a starting point at https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre/appenders/example.clj

An appender's basically just a map with some config keys and a `(fn [data-map]) -> ?output`, both of which are described at https://github.com/ptaoussanis/timbre/blob/93044a4201ebcae5fc2c34c07ee19d007b73f671/src/taoensso/timbre.cljx#L61

PR welcome if anyone feels like taking a stab at this.

**Comment by seankibler** [comment]
I'm going to take a shot at this. I'll be using timbre and I'd like to contribute. My time is extremely limited but if I can just leverage the aforementioned brolog library implementation should be very easy.

**Comment by jszakmeister** [comment]
Not that the syslog API is changing much, but how do you feel about using a library that hasn't been touched in several years?  I'm assuming that's okay?
