### ISSUE TITLE
how to disable rate limiting for an appender?

### ISSUE THREAD

**Issue by tcrayford** [ptaoussanis/timbre#76]
Hi there,

I'm trying to get Timbre to not rate limit my appender when calling `error` in a tight loop

(I tweeted about this here): https://twitter.com/t_crayford/status/498479067365396480 and https://twitter.com/t_crayford/status/498479149951242240, you asked me to file an issue.

Here's that issue:

How do I get timbre to not rate limit appenders at all? Here's roughly the code I'm using:

```clojure
(do
  (require '[taoensso.timbre :as timbre])
  (require '[yeller-timbre-appender :reload true])
  (timbre/set-config! [:appenders :yeller]
    (yeller-timbre-appender/make-yeller-appender
      {:token "YOUR TOKEN"
       :environment "timebre-test"}))
  (dotimes [_ 100] (timbre/error (ex-info "lol" {:foo 1}))))
```

`make-yeller-appender` just returns a normal appender with a map, it doesn't set rate limit (and I've tried with `:rate-limit nil` as well). I put a `println` in there and it only logged 10 times, despite the `100` times I called the `error` macro.

**Comment by tcrayford** [comment]
I figured this out recently - my appender was incorrectly using apache's http client connection pools, and throwing on all connections after the first (but not logging that it threw). Fixed now.

**Comment by ptaoussanis** [comment]
Thanks Tom, appreciate the follow-up. Cheers! :-)
