### ISSUE TITLE
Logfile rotation?

### ISSUE THREAD

**Issue by AeroNotix** [ptaoussanis/timbre#85]
Does timbre do logfile rotation by default?

I saw `rotor` but it seems this is a particular file handler. It'd be good if you provided the functions to rotate files as well.

**Comment by AeroNotix** [comment]
Ah great so log rotation is available in Timbre now for all appenders?

**Comment by ptaoussanis** [comment]
No, sorry - no change since last post. Still open to a PR if you'd like to submit something though.

Cheers! :-)
