### ISSUE TITLE
encore 1.8.1

### ISSUE THREAD

**Issue by narkisr** [ptaoussanis/timbre#92]
Seems as if 3.1.3 depnds on encore 1.8.1 however this version isn't available on Clojars

**Comment by ptaoussanis** [comment]
Hi Ronen, thanks for bringing this to my attention. Not sure how it happened - v1.8.1 should be on Clojars. In any case, you can use Timbre with the latest version of Encore: `[com.taoensso/encore "1.21.0"]`.

Also just cut a [new Timbre release](https://github.com/ptaoussanis/timbre/releases) that bumps this (+ other) deps. Cheers! :-)
