### ISSUE TITLE
Is there a way for Timbre to create log location on disk if it does not exist ?

### ISSUE THREAD

**Issue by rossputin** [ptaoussanis/timbre#93]
I may have missed this, but I did not spot it in the readme, or with a quick glance over the API docs.

Thanks.

**Comment by ptaoussanis** [comment]
Hi Ross,

Not currently. You'll normally want to do that with something like a bash script or some Java, e.g:
```clojure
(import java.io.File)
(defn exists? [path] (when-not (str/blank? path) (.exists (File. ^String path))))
(defn mkdirs "Creates all parent directories for the passed file."
  [^File f] (.mkdirs (.getParentFile (.getCanonicalFile f))))
```

Does that help?

**Comment by rossputin** [comment]
Hi.

Yes thanks, I was just being lazy, seeing if this was already handled :-)

**Comment by ptaoussanis** [comment]
Tbh it's something that the file-based appenders should probably already be doing automatically. If they're not, would be happy to accept a PR that added this. I don't use/maintain any of the file appenders myself so not actually sure how they work currently :-)

**Comment by ptaoussanis** [comment]
This will be addressed in v4, closing.
